(function () {
  var root = (window.__huntV2 = window.__huntV2 || {});

  var NON_DISCLOSURE_ALIASES = [
    "I choose not to disclose",
    "Choose not to disclose",
    "Prefer not to disclose",
    "I prefer not to answer",
    "Prefer not to answer",
    "I prefer not to respond",
    "I prefer not to respond (Canada)",
    "I do not wish to share",
    "I do not wish to share (United States of America)",
    "Prefer not to respond",
    "Prefer not to respond (Canada)",
    "I prefer not to identify",
    "Prefer not to identify",
    "I decline to disclose",
    "I do not want to answer",
    "I do not want to answer (United States of America)",
    "I don't want to answer",
    "I do not wish to answer",
    "I DO NOT WISH TO ANSWER",
    "I CHOOSE NOT TO SELF-IDENTIFY",
    "I DO NOT WISH TO SELF-IDENTIFY",
    "I DO NOT WISH TO SELF IDENTIFY",
    "I don't wish to answer",
    "I DON'T WISH TO ANSWER",
    "Don't wish to answer",
    "I do not wish to answer.",
    "I do not wish to answer (United States of America)",
    "I do not wish to answer. (United States of America)",
    "I don't wish to answer (United States of America)",
    "Undeclared/Diverse",
    "Undeclared / Diverse",
    "Undeclared",
    "Decline to State",
    "Decline to State (United States of America)",
    "Declined to State",
    "Declined to State (United States of America)",
    "Declined to Identify",
    "Declined to Identify (United States of America)",
    "Do not wish to disclose",
    "I do not wish to self-identify",
    "Decline to answer",
    "Not disclosed",
    "Undisclosed",
    "Undisclosed (United States of America)",
    "Not declared",
    "Not Declared",
    "Not specified",
    "Not Specified",
    "Not specified (United States of America)",
    "Not Specified (United States of America)",
    "None of these",
    "None of the above",
    "I do not declare",
    "Do not declare",
  ];

  function entry(id, config) {
    return Object.assign(
      {
        id: id,
        exactLabels: [],
        aliases: [],
        includeKeywords: [],
        excludeKeywords: [],
        profilePaths: [],
        defaultValue: "",
        answerType: "text",
        optionAliases: {},
      },
      config || {},
    );
  }

  var QUESTION_CATALOG = [
    entry("first_name", {
      exactLabels: ["legal name first name"],
      aliases: ["first name", "given name", "legal first name"],
      profilePaths: ["firstName"],
    }),
    entry("preferred_name", {
      aliases: ["preferred name", "preferred first name", "chosen name"],
      profilePaths: ["preferredName"],
    }),
    entry("middle_name", {
      aliases: ["middle name", "legal middle name"],
      profilePaths: ["middleName"],
    }),
    entry("last_name", {
      exactLabels: ["legal name last name"],
      aliases: ["last name", "surname", "family name", "legal last name"],
      profilePaths: ["lastName"],
    }),
    entry("name_prefix", {
      aliases: ["prefix", "name prefix", "legal name prefix", "title"],
      profilePaths: ["namePrefix"],
      answerType: "option",
      optionAliases: {
        "No Prefix": ["None", "No Prefix"],
      },
    }),
    entry("name_suffix", {
      aliases: ["suffix", "name suffix", "legal name suffix"],
      profilePaths: ["nameSuffix"],
      answerType: "option",
    }),
    entry("full_name", {
      exactLabels: ["name"],
      aliases: [
        "full name",
        "legal name",
        "candidate name",
        "applicant name",
        "enter your name",
        "please enter your name",
      ],
      profilePaths: ["fullName"],
    }),
    entry("application_company", {
      aliases: ["company name", "company", "employer", "organization"],
      profilePaths: ["applicationCompany"],
    }),
    entry("application_position", {
      aliases: [
        "position applied for",
        "position",
        "job title",
        "role applied for",
        "application role",
      ],
      profilePaths: ["applicationPosition"],
    }),
    entry("email", {
      aliases: ["email", "e-mail", "email address", "contact email"],
      profilePaths: ["email"],
    }),
    entry("account_password", {
      aliases: [
        "password",
        "new password",
        "verify new password",
        "confirm password",
      ],
      excludeKeywords: [
        "current password",
        "old password",
        "existing password",
        "temporary password",
      ],
      profilePaths: ["accountPassword"],
    }),
    entry("phone", {
      aliases: ["phone", "phone number", "mobile", "cell", "telephone"],
      profilePaths: ["phone"],
    }),
    entry("phone_device_type", {
      aliases: ["phone device type", "phone type", "device type"],
      profilePaths: ["phoneDeviceType"],
      defaultValue: "Mobile",
      optionAliases: {
        Mobile: [
          "Cell",
          "Cell Phone",
          "Cellular",
          "Mobile",
          "Mobile Phone",
          "Personal Mobile",
        ],
      },
    }),
    entry("phone_country_code", {
      aliases: [
        "phone country code",
        "country phone code",
        "country / territory phone code",
      ],
      profilePaths: ["phoneCountryCode"],
      defaultValue: "Canada (+1)",
      optionAliases: { "Canada (+1)": ["Canada", "+1", "CA +1"] },
    }),
    entry("workday_system_usage", {
      aliases: [
        "use or work on the workday system",
        "work on the workday system",
        "current job do you use or work",
      ],
      excludeKeywords: ["describe your interactions", "describe interactions"],
      defaultValue: "No, I do not use the Workday system in my current job",
    }),
    entry("truthful_application_acknowledgement", {
      aliases: [
        "please enter yes if you acknowledge",
        "acknowledge that you have read",
        "acknowledge that you understand",
        "truthfully and accurately",
        "information is true",
      ],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("identity_verification_upon_hire", {
      aliases: [
        "provide verification of your identity upon hire",
        "provide verification of your identify upon hire",
        "provide proof of identity upon hire",
        "verify your identity upon hire",
        "identity verification upon hire",
      ],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("relocation_willingness", {
      aliases: [
        "are you willing to relocate",
        "are you willing to relocate if needed",
        "would you be willing to relocate",
        "would you be willing to relocate if needed",
        "position is not located in the city that you reside in",
        "not located in the city that you reside in",
      ],
      profilePaths: ["willingToRelocate"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("job_area_location", {
      aliases: [
        "currently located in the area where the job is located",
        "currently located in the area where this job is located",
        "currently located in the area where the position is located",
        "currently located in the job area",
        "located in the area where the job is located",
      ],
      profilePaths: ["currentlyInJobArea", "openToAnyLocation"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("commute_willingness", {
      aliases: [
        "willing to commute",
        "willing to commute to the area",
        "commute to the area where this position is located",
        "commute to the area where the position is located",
        "commute to the work location",
        "work-location willingness",
        "work location willingness",
      ],
      profilePaths: ["commuteWillingness", "workLocationWillingness"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("relocation_consideration", {
      aliases: [
        "would you consider relocating for this role",
        "would consider relocating for this role",
      ],
      profilePaths: ["relocationPreference", "willingToRelocate"],
      defaultValue: true,
      answerType: "yes_no",
      optionAliases: {
        Yes: [
          "Yes",
          "Yes, I would consider relocating for this role",
          "I would consider relocating for this role",
        ],
        No: [
          "No",
          "No, I would not consider relocating for this role",
          "I would not consider relocating for this role",
        ],
      },
    }),
    entry("temporary_short_contract_interest", {
      aliases: [
        "temporary / short-contract basis",
        "temporary short-contract basis",
        "temporary or short-contract basis",
        "temporary basis",
        "short-contract basis",
        "short contract basis",
        "interested in working on a temporary",
        "interested in hearing about contract roles",
        "hearing about contract roles",
        "contract roles",
      ],
      excludeKeywords: [
        "temporary password",
        "temporary work permit",
        "temporary sin",
        "temporary social insurance",
        "temporary resident",
      ],
      profilePaths: ["interestedTemporaryShortContract"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("non_compete_restriction", {
      aliases: [
        "non-compete or non-solicitation restrictions",
        "non compete or non solicitation restrictions",
        "contractual restrictions on your ability to work",
        "contractual restrictions exist",
        "bound by any non-solicitation agreements",
        "non-solicitation agreements which would restrict your ability",
        "restrict your ability to prospect for business",
        "bound by a continuing confidentiality or patent agreement",
        "agreements that contain a restrictive covenant",
        "non-compete, non-solicitation or non-disclosure",
        "restrictive agreement",
        "restrictive agreements",
        "subject to any restrictive agreement",
        "restrict your ability to work",
        "limit your ability to work",
        "restrictive covenant",
        "agreement or policy",
        "prohibit or restrict you from recruiting",
        "hiring former colleagues",
        "soliciting/doing business with customers",
        "soliciting or doing business with customers",
        "limit your ability to compete",
        "accept an offer of employment",
        "current or former employer",
        "equity awards such as restricted stock units",
        "prohibit or restrict your ability to perform",
        "perform the duties of this position",
      ],
      profilePaths: ["restrictiveAgreement", "nonCompeteRestriction"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("current_company_employee", {
      aliases: [
        "do you currently work at",
        "currently work at cvs health",
        "current employee of cvs health",
      ],
      profilePaths: ["currentEmployers"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("conflict_of_interest_relationship", {
      aliases: [
        "avoid conflicts of interest",
        "relatives romantic partners",
        "people with whom you share a dwelling",
        "business relationship with who work",
        "work in any capacity at bms",
        "conflict of interest relationship",
      ],
      profilePaths: ["conflictOfInterestRelationship"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("outside_conflict_none", {
      aliases: [
        "do you intend to select all that apply",
        "secondary non-intel employment",
        "secondary employment",
        "sit on the board",
        "board of directors",
        "conflict of interest",
      ],
      defaultValue: "Neither",
      answerType: "option",
      optionAliases: {
        Neither: ["Neither", "None of these", "None of the above"],
      },
    }),
    entry("hhs_oig_exclusion", {
      aliases: [
        "hhs/oig list of excluded individuals/entities",
        "hhs oig list of excluded individuals entities",
        "list of excluded individuals/entities",
        "oig.hhs.gov",
      ],
      profilePaths: ["hhsOigExcluded"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("gsa_federal_program_exclusion", {
      aliases: [
        "general services administration's list of parties excluded from federal programs",
        "general services administration list of parties excluded from federal programs",
        "list of parties excluded from federal programs",
        "excluded from federal programs",
        "epls.gov",
      ],
      profilePaths: ["gsaFederalProgramExcluded"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("generic_drug_enforcement_debarment", {
      aliases: [
        "debarred under the generic drug enforcement act",
        "generic drug enforcement act of 1992",
      ],
      profilePaths: ["genericDrugDebarred"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("debarment_proceedings_pending", {
      aliases: [
        "debarment proceedings pending",
        "debarment proceedings pending or to your knowledge threatened",
        "to your knowledge threatened",
      ],
      profilePaths: ["debarmentProceedingsPending"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("us_licensed_physician", {
      aliases: [
        "us licensed physician",
        "u.s. licensed physician",
        "do you possess a current license",
        "do you hold a current license",
        "active healthcare license",
        "healthcare license",
        "professional license required",
      ],
      profilePaths: ["usLicensedPhysician"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("fda_hhs_investigational_drug_restriction", {
      aliases: [
        "disqualified or restricted by the fda or hhs",
        "receiving investigational drugs",
        "investigated for or disqualified or restricted",
      ],
      profilePaths: ["fdaHhsInvestigationalDrugRestricted"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("governmental_or_licensing_inquiry", {
      aliases: [
        "pending inquiry by any governmental entity or licensing association",
        "administrative action been imposed upon you by any governmental entity",
        "governmental entity or licensing association",
        "not requesting any information relating to criminal arrests",
      ],
      profilePaths: ["governmentalLicensingInquiry"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("professional_license_discipline", {
      aliases: [
        "disciplinary action taken on your professional license",
        "disciplinary action taken on your professional license, certification, or credentials",
        "anticipate receiving any disciplinary action",
        "fines, citations, penalties, reprimands",
        "probation, restrictions, revocation",
        "suspension, surrender, or voluntary surrender",
        "insurance license refused",
        "insurance licence refused",
        "insurance license revoked",
        "insurance licence revoked",
        "insurance license suspended",
        "insurance licence suspended",
        "license ever been refused",
        "licence ever been refused",
        "license ever been revoked",
        "licence ever been revoked",
        "license ever been suspended",
        "licence ever been suspended",
      ],
      profilePaths: [
        "professionalLicenseDiscipline",
        "insuranceLicenseRefusedRevokedSuspended",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("regulated_cannabis_liquor_license", {
      aliases: [
        "valid license to sell cannabis/liquor",
        "valid license to sell cannabis liquor",
        "license to sell cannabis",
        "license to sell liquor",
        "cannabis/liquor in canada",
        "cannabis liquor in canada",
        "qualified cannabis worker",
        "sell cannabis or liquor",
      ],
      profilePaths: ["cannabisLiquorSalesLicense", "regulatedSalesLicense"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("government_exclusion_or_debarment", {
      aliases: [
        "excluded, debarred, suspended",
        "excluded debarred suspended",
        "ineligible from participation in any federal or state healthcare program",
        "debarred or suspended",
        "federal debarment",
      ],
      profilePaths: ["debarredOrSuspended"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("government_procurement_disclosure", {
      aliases: [
        "department of defense contract award",
        "department of defense contract administration",
        "dod contract award",
        "dod contract administration",
        "government procurement",
        "procurement disclosure",
      ],
      profilePaths: ["governmentProcurementHistory"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("foreign_pharmacist_licensure_hours", {
      aliases: [
        "pharmacist from another country needing hours towards licensure",
        "another country needing hours towards licensure",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("sms_communication_authorization", {
      aliases: [
        "authorize cvs health to communicate with me via text",
        "communicate with me via text",
        "standard message rates may apply",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("proof_of_us_work_authorization", {
      aliases: [
        "provide proof that you are legally able to work in the united states",
        "legally able to work in the united states",
        "verify identity and eligibility to work in the united states",
      ],
      profilePaths: ["workAuthorized"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("government_official", {
      aliases: [
        "are you or have you been within the last 12 months a government official",
        "are you a government official",
        "have you been a government official",
        "government official",
        "current or former employee of the united states government",
        "former employee of the united states government",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("politically_exposed_person", {
      aliases: [
        "politically exposed person",
        "politically exposed persons",
        "politically exposed foreign person",
        "pep",
        "senior political figure",
        "head of state",
        "head of government",
        "senior politician",
        "senior government official",
        "close associate of a politically exposed",
        "close associate of a pep",
        "family member of a politically exposed",
        "family member of a pep",
        "associated with a politically exposed",
      ],
      profilePaths: [
        "politicallyExposedPerson",
        "pepStatus",
        "closeAssociatePoliticallyExposedPerson",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("export_control_restricted_region", {
      aliases: [
        "export control laws",
        "current citizen, national or resident",
        "current citizen national or resident",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("us_person_export_control", {
      aliases: [
        "u.s. person",
        "us person",
        "united states person",
        "u.s. citizen",
        "us citizen",
        "u.s. national",
        "lawful permanent resident",
        "green card holder",
        "refugee or asylee",
        "export-control purposes",
        "export control purposes",
      ],
      excludeKeywords: [
        "are you a citizen of the united states",
        "are you a united states citizen",
      ],
      profilePaths: ["usPersonForExportControl"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("us_citizen", {
      aliases: [
        "are you a citizen of the united states",
        "are you a united states citizen",
        "are you a u.s. citizen",
        "are you a us citizen",
      ],
      profilePaths: ["usCitizen"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("us_federal_employment_current", {
      aliases: [
        "current u.s. federal government civilian or military",
        "current us federal government civilian or military",
        "currently a u.s. federal government civilian",
        "currently a us federal government civilian",
        "active duty or reserves employee",
      ],
      profilePaths: ["currentUsFederalEmployeeOrMilitary"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("us_federal_employment_former", {
      aliases: [
        "former u.s. federal government civilian or military",
        "former us federal government civilian or military",
        "formerly a u.s. federal government civilian",
        "formerly a us federal government civilian",
        "former active duty or reserves employee",
      ],
      profilePaths: ["formerUsFederalEmployeeOrMilitary"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("us_citizenship_status", {
      aliases: [
        "citizenship status",
        "u.s. status",
        "us status",
        "u.s.-status citizenship",
        "us-status citizenship",
      ],
      excludeKeywords: [
        "canadian citizenship status",
        "provide your canadian citizenship status",
      ],
      profilePaths: ["usCitizenshipStatus"],
      defaultValue: "Other",
      answerType: "option",
      optionAliases: {
        Other: ["Other", "None of the above"],
      },
    }),
    entry("us_citizenship_status_explanation", {
      aliases: [
        "if you responded other please explain",
        'if you responded "other", please explain',
        "if you selected other please explain",
        "citizenship status other explanation",
      ],
      profilePaths: ["usCitizenshipStatusExplanation", "citizenship"],
      defaultValue: "Canadian citizen",
    }),
    entry("active_security_clearance", {
      aliases: [
        "do you have an active clearance",
        "active clearance",
        "currently hold a security clearance",
        "active security clearance",
      ],
      profilePaths: ["activeClearance", "activeSecurityClearance"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("related_current_employee", {
      aliases: [
        "related to a current workday employee",
        "related to a current employee",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("related_customer_or_government_official", {
      aliases: [
        "direct business interactions with workday",
        "related to an employee of a customer",
        "related to a government official",
        "immediate family members government officials",
        "family members government officials",
        "family member government official",
        "employee of any government department agency",
        "organization owned fully or partially by government",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("gender_disclosure_neutral", {
      aliases: [
        "please select your gender",
        "what is your sex",
        "sex",
        "birth sex",
        "gender identity",
        "gender expression",
      ],
      defaultValue: "Not Declared",
      answerType: "non_disclosure",
      optionAliases: {
        "Not Declared": [
          "Not Declared",
          "I choose not to disclose",
          "I do not want to answer",
          "I do not wish to answer",
          "Prefer not to answer",
        ],
      },
    }),
    entry("ethnicity_disclosure_neutral", {
      aliases: [
        "ethnicity which most accurately describes",
        "what is your ethnicity",
        "ethnicity",
        "ethnicities",
        "ethnicity(ies)",
        "please select the ethnicity",
        "personalinfoperson--ethnicities",
        "ethno-racial identity",
        "ethno racial identity",
        "ethno-racial identities",
        "ethno racial identities",
        "race/ethnicity",
        "race ethnicity",
      ],
      defaultValue: "I decline to disclose",
      answerType: "non_disclosure",
      optionAliases: {
        "I decline to disclose": [
          "I decline to disclose",
          "I choose not to disclose",
          "I do not want to answer",
          "I do not want to answer (United States of America)",
          "I do not wish to answer",
          "I do not wish to share",
          "I do not wish to share (United States of America)",
          "I do not wish to answer.",
          "I do not wish to answer (United States of America)",
          "I do not wish to answer. (United States of America)",
          "Decline to State",
          "Decline to State (United States of America)",
          "Prefer not to answer",
          "Prefer not to respond",
          "Prefer not to respond (Canada)",
          "Not Specified",
          "Not Specified (United States of America)",
          "Not Declared",
        ],
      },
    }),
    entry("veteran_disclosure_neutral", {
      aliases: [
        "please provide your current veteran status",
        "current veteran status",
        "are you a veteran",
        "veteran status",
        "protected veteran",
      ],
      defaultValue: "I CHOOSE NOT TO SELF-IDENTIFY",
      answerType: "non_disclosure",
      optionAliases: {
        "I CHOOSE NOT TO SELF-IDENTIFY": [
          "I CHOOSE NOT TO SELF-IDENTIFY",
          "I DON'T WISH TO ANSWER",
          "I DO NOT WISH TO ANSWER",
          "I choose not to disclose",
          "Not Declared",
        ],
      },
    }),
    entry("city", {
      exactLabels: ["address city"],
      aliases: ["city", "current city", "home city"],
      profilePaths: ["city"],
    }),
    entry("province", {
      aliases: ["province", "state", "province territory", "region"],
      profilePaths: ["province"],
      optionAliases: {
        Alberta: ["AB"],
        "British Columbia": ["BC", "B.C."],
        Manitoba: ["MB"],
        "New Brunswick": ["NB"],
        "Newfoundland and Labrador": ["NL"],
        "Northwest Territories": ["NT"],
        "Nova Scotia": ["NS"],
        Nunavut: ["NU"],
        Ontario: ["ON"],
        "Prince Edward Island": ["PE", "PEI"],
        Quebec: ["QC"],
        Saskatchewan: ["SK"],
        Yukon: ["YT"],
      },
    }),
    entry("country", {
      aliases: [
        "country",
        "current country",
        "country territory",
        "country region",
      ],
      profilePaths: ["country"],
      defaultValue: "Canada",
    }),
    entry("location", {
      aliases: ["location", "current location", "where are you located"],
      profilePaths: ["location"],
    }),
    entry("city_province_location", {
      aliases: [
        "city province",
        "city province are you located in",
        "what city province are you located in",
      ],
      profilePaths: ["location"],
    }),
    entry("address_line_1", {
      aliases: ["address line 1", "street address", "address"],
      profilePaths: ["addressLine1"],
    }),
    entry("address_line_2", {
      aliases: ["address line 2", "apartment", "unit"],
      profilePaths: ["addressLine2"],
    }),
    entry("postal_code", {
      aliases: ["postal code", "zip code"],
      profilePaths: ["postalCode"],
    }),
    entry("linkedin", {
      aliases: ["linkedin", "linkedin url", "linkedin profile"],
      profilePaths: ["linkedinUrl"],
    }),
    entry("github", {
      aliases: ["github", "github url", "github profile"],
      profilePaths: ["githubUrl"],
    }),
    entry("website", {
      aliases: ["website", "portfolio", "personal site"],
      profilePaths: ["websiteUrl"],
    }),
    entry("technical_skills", {
      aliases: [
        "type to add skills",
        "add skills",
        "skills describe your knowledge",
        "skills",
      ],
      profilePaths: ["skills", "skillList", "technicalSkills"],
    }),
    entry("resume_upload", {
      aliases: [
        "resume",
        "cv",
        "resume/cv",
        "upload a file",
        "select files",
        "select file",
        "drop files",
      ],
      defaultValue: "resume_upload",
      answerType: "file",
    }),
    entry("application_source", {
      aliases: ["how did you hear", "source", "application source"],
      profilePaths: [
        "applicationSourceCategory",
        "applicationSource",
        "applicationSourceDetail",
      ],
      defaultValue: "LinkedIn",
    }),
    entry("alternative_positions_interest", {
      aliases: [
        "considered for alternative positions",
        "considered for alternate positions",
        "alternative positions",
        "alternate positions",
        "future positions",
        "future opportunities",
      ],
      profilePaths: ["alternativePositionsInterest"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("terms_acceptance", {
      aliases: [
        "terms and conditions",
        "accept terms",
        "accept terms and agreements",
        "read and consent",
        "consent to the terms",
        "agree with the terms",
        "agree with the terms and conditions",
        "career privacy notice",
        "privacy notice",
        "agree to the above career privacy notice",
        "candidate privacy statement",
        "candidate acknowledgment",
        "candidate acknowledgement",
        "by continuing, you agree",
        "check the box to continue",
        "agree to creating this account",
        "creating this account",
        "create account checkbox",
        "createaccountcheckbox",
        "allow me to apply",
        "account to allow me to apply",
        "accepttermsandagreements",
        "non disclosure agreement",
        "non-disclosure agreement",
        "arbitration agreement",
        "mutual arbitration agreement",
      ],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("sms_application_contact_opt_out", {
      aliases: [
        "reach out to me via sms",
        "sms regarding my application",
        "sms regarding my application and candidate experience",
        "message and data rates may apply",
        "i can opt-out at any time",
      ],
      defaultValue: "Opt-Out",
      optionAliases: {
        "Opt-Out": [
          "Opt-Out",
          "Opt Out",
          "OptOut",
          "No, I do not wish to receive SMS/Text messages",
          "No, I do not wish to receive SMS messages",
          "No, I do not wish to receive text messages",
        ],
      },
    }),
    entry("preferred_communication_channel", {
      aliases: [
        "preferred communication channel",
        "please select your preferred communication channel",
        "preferred method of communication",
        "preferred method of communication should we want to contact you",
      ],
      profilePaths: ["preferredCommunicationChannel"],
      defaultValue: "Email",
      answerType: "option",
      optionAliases: {
        Email: ["E-mail", "Email Address", "Personal Email", "Work Email"],
      },
    }),
    entry("preferred_language", {
      aliases: [
        "preferred language",
        "please select your preferred language",
        "preferred interview language",
        "interview language",
      ],
      profilePaths: ["preferredLanguage"],
      defaultValue: "English",
      answerType: "option",
      optionAliases: {
        English: ["English", "Anglais"],
      },
    }),
    entry("aedt_processing_opt_out_request", {
      aliases: [
        "request to opt-out of the use of an aedts",
        "request to opt out of the use of an aedts",
        "opt-out of the use of an aedts in the recruitment process",
        "opt out of the use of an aedts in the recruitment process",
      ],
      profilePaths: ["automatedDecisionToolOptOut"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("automated_ai_processing_opt_out", {
      aliases: [
        "automated tools such as ai",
        "support review of your application",
        "match you with relevant existing and future open roles",
        "prefer not to have your application processed by these tools",
        "opting out will not impact your eligibility",
      ],
      defaultValue: "Opt-Out",
      optionAliases: {
        "Opt-Out": ["Opt-Out", "Opt Out", "OptOut"],
      },
    }),
    entry("ai_recruiting_tools_consent", {
      aliases: [
        "ai-enabled recruiting tools",
        "ai enabled recruiting tools",
        "ai-enabled tools",
        "ai enabled tools",
        "artificial intelligence enabled tools",
        "artificial intelligence recruiting tools",
        "recruiting tools consent",
        "consent to use ai",
        "use of ai-enabled tools",
        "use of ai enabled tools",
        "use of artificial intelligence",
      ],
      excludeKeywords: [
        "opt-out",
        "opt out",
        "prefer not to have your application processed",
      ],
      profilePaths: ["aiRecruitingToolsConsent"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("talent_community_opt_in", {
      aliases: [
        "talent community",
        "marketing opt-in",
        "marketing opt in",
        "future job opportunities",
        "future opportunities",
        "keep me informed",
        "contact me about future",
      ],
      profilePaths: ["talentCommunityOptIn", "futureOpportunitiesOptIn"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("future_communications_opt_in", {
      aliases: [
        "future communications",
        "future employer communications",
        "receive communications about future",
        "contacted about future opportunities",
      ],
      profilePaths: ["futureCommunicationsOptIn"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("current_date", {
      aliases: [
        "today's date",
        "todays date",
        "enter today's date",
        "enter todays date",
        "please enter today's date",
        "please enter todays date",
        "date signed",
        "date signed on",
        "signed on",
      ],
      excludeKeywords: [
        "18 years",
        "years of age",
        "years old",
        "age or older",
      ],
      defaultValue: "today",
    }),
    entry("has_bachelors_degree", {
      aliases: [
        "do you have a bachelor's degree",
        "do you have a bachelors degree",
        "have a bachelor's degree",
        "have a bachelors degree",
      ],
      profilePaths: ["highestEducation", "degreeLevel"],
      defaultValue: false,
      answerType: "education_level_yes_no",
      expectedEducationLevel: "bachelors",
    }),
    entry("high_school_diploma_or_higher", {
      aliases: [
        "did you receive your high school diploma",
        "received your high school diploma",
        "have you received your high school diploma",
        "do you have a high school diploma",
        "high school diploma or equivalent",
        "high school diploma or ged",
      ],
      profilePaths: ["highestEducation", "degreeLevel"],
      defaultValue: false,
      answerType: "education_level_yes_no",
      expectedEducationLevel: "high_school",
    }),
    entry("work_authorized", {
      aliases: [
        "authorized to work",
        "able to legally work",
        "eligible to work",
        "entitled to work",
        "legally entitled to work",
        "legally allowed to work",
        "legally authorized",
        "legally permitted to work",
        "permitted to work",
        "legal right to work",
        "right to work in the country",
        "work authorization",
      ],
      excludeKeywords: ["sponsor", "sponsorship"],
      profilePaths: ["workAuthorized"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("sponsorship_required", {
      aliases: [
        "sponsor",
        "sponsorship",
        "require intel to sponsor",
        "require intel to sponsor a visa petition",
        "require employer immigration sponsorship",
        "require employer immigration sponsorship now or in the future",
        "require sponsorship now or in the future",
        "will you in the future require",
        "visa support",
        "visa petition",
        "employer-provided visa sponsorship",
        "immigration support",
      ],
      profilePaths: ["sponsorshipRequired"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("open_work_permit", {
      aliases: [
        "currently on an open work permit",
        "on an open work permit",
        "open work permit",
      ],
      profilePaths: ["openWorkPermit"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("canadian_citizenship_status", {
      aliases: [
        "canadian citizenship status",
        "provide your canadian citizenship status",
        "citizenship status to assist us",
      ],
      excludeKeywords: [
        "sponsor",
        "sponsorship",
        "visa",
        "visa petition",
        "work authorization application",
      ],
      profilePaths: ["canadianCitizenOrPermanentResident"],
      defaultValue: "Citizen (Canada)",
    }),
    entry("sanctioned_country_citizenship", {
      aliases: [
        "please indicate which if any where you are a citizen",
        "indicate which if any where you are a citizen",
        "which if any where you are a citizen",
        "where you are a citizen",
        "cuba syria north korea iran sudan none of these",
      ],
      defaultValue: "None of these",
      answerType: "option",
      optionAliases: {
        "None of these": ["None of these", "None"],
      },
    }),
    entry("secondary_citizenship", {
      aliases: [
        "secondary citizenship",
        "secondary country of citizenship",
        "second citizenship",
        "second country of citizenship",
        "additional citizenship",
        "additional country of citizenship",
        "other citizenship",
        "other country of citizenship",
        "dual citizenship",
      ],
      profilePaths: ["secondaryCitizenship", "secondCitizenship"],
      defaultValue: "None of these",
      answerType: "option",
      optionAliases: {
        "None of these": NON_DISCLOSURE_ALIASES.concat([
          "None",
          "No",
          "No Secondary Citizenship",
          "No secondary citizenship",
          "No other citizenship",
          "No additional citizenship",
        ]),
      },
    }),
    entry("citizenship", {
      aliases: [
        "country of citizenship",
        "citizenship country",
        "citizenship",
        "nationality",
        "country of nationality",
      ],
      excludeKeywords: [
        "sponsor",
        "sponsorship",
        "visa",
        "visa petition",
        "work authorization application",
        "secondary",
        "second",
        "additional",
        "other",
        "dual",
        "which if any where you are a citizen",
      ],
      profilePaths: ["citizenship", "primaryCitizenship", "country"],
      defaultValue: "Canada",
      answerType: "option",
      optionAliases: {
        Canada: ["Canada", "Citizen (Canada)", "Canadian", "Canada citizen"],
      },
    }),
    entry("canadian_citizen_pr", {
      aliases: ["canadian citizen", "permanent resident"],
      excludeKeywords: [
        "sponsor",
        "sponsorship",
        "visa",
        "visa petition",
        "work authorization application",
      ],
      profilePaths: ["canadianCitizenOrPermanentResident"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("sin_starts_with_nine", {
      aliases: [
        "social insurance number sin that begins with the number 9",
        "sin that begins with the number 9",
        "sin begins with the number 9",
        "sin starts with 9",
        "sin starts with the number 9",
      ],
      profilePaths: ["sinStartsWithNine"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("previous_employer", {
      aliases: [
        "previously worked",
        "previously employed",
        "previously been employed",
        "previously employed by",
        "previously or are you currently engaged",
        "employed in the past",
        "employed by",
        "have you been employed by",
        "ever worked for",
        "worked for",
        "worked at",
        "former employee",
        "contractor consultant former employee",
        "access to bms systems",
        "employee or as a contractor",
        "employee or contractor",
        "directly employed",
        "accepted an offer",
        "contracted with",
        "subsidiary",
        "affiliates",
        "affiliate",
        "company that was acquired by",
        "merged with",
        "co-op or internship",
        "coop or internship",
        "work with us before",
        "worked with us before",
        "previously, or do you currently, work",
        "previously or do you currently work",
        "parent company",
        "current employee",
        "current atco employee",
      ],
      profilePaths: ["previousEmployers"],
      defaultValue: false,
      answerType: "exact_previous_employer",
    }),
    entry("prior_temp_staffing_agency", {
      aliases: [
        "employed via a temporary staffing agency",
        "employed at nait via a temporary staffing agency",
        "temporary staffing agency",
        "through a staffing agency",
      ],
      profilePaths: ["priorTempStaffingAgency"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("previous_application", {
      aliases: [
        "have you ever applied for employment with this company",
        "applied for employment with this company",
        "previously applied",
        "applied previously",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("prior_termination_or_resignation", {
      aliases: [
        "have you ever been terminated",
        "ever been terminated",
        "terminated or asked to resign",
        "asked to resign from employment",
        "asked to resign",
        "discharged from employment",
        "involuntarily terminated",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("referral_or_family", {
      aliases: [
        "referral",
        "know anyone",
        "family member",
        "relative",
        "relatives employed",
        "relatives currently employed",
        "relatives at",
        "family employed",
        "domestic partner",
      ],
      profilePaths: ["familyMemberAtCompany"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("background_check_consent", {
      aliases: [
        "willing to complete a background",
        "willing to complete a background security check",
        "willing to complete a criminal background check",
        "able to clear a criminal background check",
        "complete a background security check",
        "complete a background check",
        "clear a criminal background check",
        "criminal record and references",
        "reference check",
        "background screening",
        "identity verification",
        "drug testing",
        "drug test",
        "pre-employment drug screening",
        "understand and consent to background",
      ],
      excludeKeywords: ["convicted", "criminal offence", "criminal offense"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("criminal_conviction_unpardoned", {
      aliases: [
        "convicted of a criminal offence for which a pardon has not been granted",
        "convicted of a criminal offense for which a pardon has not been granted",
        "criminal offence for which a pardon has not been granted",
        "criminal offense for which a pardon has not been granted",
        "unpardon",
        "unpardoned",
      ],
      profilePaths: ["criminalConvictionUnpardoned"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("legal_age_industry_eligibility", {
      aliases: [
        "legal age to work",
        "of legal age to work",
        "legal age to work in the cannabis",
        "legal age to work in the cannabis liquor industry",
        "legal age to work in the liquor industry",
      ],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("essential_functions", {
      aliases: [
        "able to perform the essential functions",
        "perform the essential functions",
        "essential functions of the position",
        "with or without reasonable accommodation",
      ],
      profilePaths: ["canPerformEssentialFunctions"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("accommodation_request", {
      aliases: [
        "require accessibility accommodations",
        "require accessibility accommodation",
        "require accessibility accommodations or adjustments",
        "require accommodations or adjustments",
        "will require accessibility accommodations",
        "will require accessibility accommodations or adjustments",
        "need support or adjustments",
        "need support or adjustment",
        "might need support or adjustments",
        "support or adjustments to make the application",
      ],
      profilePaths: ["accommodationRequest"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("reliable_transportation", {
      aliases: [
        "valid driver's license or have reliable transportation",
        "valid driver’s license or have reliable transportation",
        "drivers license or have reliable transportation",
        "driver's license or have reliable transportation",
        "reliable transportation to report to work",
        "have reliable transportation",
      ],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("union_membership", {
      aliases: [
        "member of cewa",
        "cewa",
        "union member",
        "member of a union",
        "member of union",
      ],
      profilePaths: ["cewaMember", "unionMembership"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("degree_level", {
      aliases: ["degree level", "level of education", "education level"],
      profilePaths: ["degreeLevel"],
      optionAliases: {
        "Bachelor's Degree": [
          "Bachelor's",
          "Bachelors",
          "Bachelor",
          "University",
        ],
        "Graduate School": ["Graduate School", "MBA", "PHD", "PhD", "Master"],
        Bachelors: ["Bachelor's", "Bachelor's Degree", "Bachelor"],
      },
    }),
    entry("highest_education", {
      aliases: [
        "highest education",
        "highest degree attained",
        "highest level of education",
        "highest level of completed education",
      ],
      profilePaths: ["highestEducation", "degreeLevel"],
      optionAliases: {
        "Bachelor's Degree": [
          "Bachelor's",
          "Bachelors",
          "Bachelor",
          "University",
        ],
        "Graduate School": ["Graduate School", "MBA", "PHD", "PhD", "Master"],
        Bachelors: ["Bachelor's", "Bachelor's Degree", "Bachelor"],
      },
    }),
    entry("microsoft_office_proficiency", {
      aliases: [
        "microsoft office proficiency",
        "level of computer proficiency in microsoft office",
        "computer proficiency in microsoft office",
      ],
      profilePaths: ["microsoftOfficeProficiency", "officeProficiency"],
      defaultValue: "Expert",
      optionAliases: {
        Expert: ["Expert", "Advanced", "Fluent", "Native", "Excellent"],
      },
    }),
    entry("highest_proficiency", {
      aliases: ["proficiency", "level of proficiency", "proficiency level"],
      profilePaths: ["proficiencyLevel"],
      defaultValue: "Expert",
      optionAliases: {
        Expert: ["Expert", "Advanced", "Fluent", "Native", "Excellent"],
      },
    }),
    entry("travel_availability", {
      aliases: [
        "travel is required",
        "what is your availability",
        "travel availability",
        "availability for travel",
      ],
      profilePaths: ["travelAvailability"],
      defaultValue: "highest",
      answerType: "travel_availability",
    }),
    entry("outside_conflict_activities", {
      aliases: [
        "outside activities",
        "trade groups or board memberships",
        "competitive to or in competition with",
        "conflicting outside activities",
        "possible conflicting outside activities",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("computer_programs", {
      aliases: [
        "what other computer programs have you worked in",
        "other computer programs",
        "computer programs have you worked in",
      ],
      profilePaths: [
        "computerPrograms",
        "skills",
        "skillList",
        "technicalSkills",
      ],
      defaultValue: "",
    }),
    entry("expected_graduation_year", {
      aliases: ["graduation year", "expected graduation"],
      profilePaths: ["expectedGraduationYear"],
    }),
    entry("desired_start_date", {
      aliases: [
        "desired start date",
        "available start date",
        "available to start",
        "available to start work",
        "date are you available to start work",
        "earliest date you can start",
        "if hired what is the earliest date you can start",
        "earliest availability to start this new position",
        "when is your earliest availability to start this new position",
        "how soon can you start",
        "how soon would you be available to start",
        "availability date",
        "earliest availability date",
        "earliest date that you could start work",
        "earliest date you could start work",
        "could start work",
        "accept a job offer",
        "start work date",
      ],
      profilePaths: ["desiredStartDate"],
      defaultValue: "today",
    }),
    entry("shift_availability", {
      aliases: [
        "shift availability",
        "what is your shift availability",
        "select all that apply",
        "available to work shiftwork",
        "available to work shift work",
        "are you available to work shiftwork",
        "are you available to work shift work",
        "are you open to shiftwork",
        "open to shiftwork",
        "open to shift work",
        "days, nights, weekends",
      ],
      profilePaths: ["shiftAvailability"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("work_term_availability", {
      aliases: [
        "available for the summer",
        "available for the summer 2026 term",
        "confirm you are available for the summer",
        "confirm you are available for the summer 2026 term",
      ],
      profilePaths: ["availableSummer2026", "workTermAvailability"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("interview_availability", {
      aliases: [
        "available to interview",
        "available to interview from",
        "are you available to interview",
        "interview availability",
      ],
      profilePaths: ["availableInterviewWindow", "interviewAvailability"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("coop_terms_completed", {
      aliases: [
        "co-op terms have you completed",
        "coop terms have you completed",
        "how many co-op terms",
        "how many coop terms",
      ],
      profilePaths: ["coOpTermsCompleted", "coopTermsCompleted"],
      answerType: "option",
      optionAliases: {
        0: ["0 terms completed, this will be my 1st term"],
        1: ["1 term completed, this will be my 2nd term"],
        2: ["2 terms completed, this will be my 3rd term"],
      },
    }),
    entry("full_time_part_time_preference", {
      aliases: [
        "interested in a full time or part time position",
        "full time or part time position",
      ],
      profilePaths: ["employmentTypePreference"],
      defaultValue: "Full Time",
      answerType: "option",
      optionAliases: {
        "Full Time": ["Full Time", "Full-Time"],
      },
    }),
    entry("military_spouse_partner", {
      aliases: [
        "spouse or partner of someone who serves",
        "spouse or partner of someone who served",
        "serves/served in the u.s. military",
      ],
      profilePaths: ["militarySpouseOrPartner"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("national_guard_reserves", {
      aliases: [
        "national guard",
        "national guard/reserves",
        "guard/reserves",
        "guard or reserves",
        "reserve member",
        "reserves member",
      ],
      profilePaths: ["nationalGuardOrReserves"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("age_at_least_18", {
      aliases: [
        "as of today's date are you 18 years of age or older",
        "as of todays date are you 18 years of age or older",
        "are you age 18 or over",
        "age 18 or over",
        "are you 18 years of age or older",
        "18 years of age or older",
        "are you 18 years or older",
        "18 years or older",
        "are you at least 18 years old",
        "at least 18 years old",
        "are you at least 18 years of age",
        "at least 18 years of age",
      ],
      profilePaths: ["atLeast18"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("related_experience_years", {
      aliases: [
        "how many years of related experience do you have",
        "years of related experience",
        "related experience do you have",
        "years related experience",
      ],
      profilePaths: ["relatedExperienceYearsRange"],
      defaultValue: "3",
      answerType: "year_range",
      optionAliases: {
        3: ["3-5 years", "2-5 years", "3 years"],
      },
    }),
    entry("basic_requirements_qualified", {
      aliases: [
        "basic requirements qualifications",
        "basic requirements/qualifications",
        "basic requirements for this role",
        "basic qualifications for this role",
        "meet all the basic requirements",
        "meet all the basic qualifications",
        "meet all required qualifications",
        "meet the required qualifications",
        "meet all minimum qualifications",
        "meet the minimum qualifications",
        "minimum qualifications for this role",
        "required years",
        "software language",
        "network technologies",
        "software languages and/or network technologies",
        "required software",
        "required network",
      ],
      includeKeywords: ["meet", "qualifications"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("public_sector_restriction", {
      aliases: [
        "public-sector restrictions",
        "public sector restrictions",
        "post-government restriction",
        "government restriction",
        "restricted from working with public sector",
        "suspended or debarred",
        "future communications",
      ],
      profilePaths: ["publicSectorRestriction", "debarredOrSuspended"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("experience_affirmation", {
      aliases: [
        "do you have experience",
        "do you have relevant experience",
        "relevant work experience",
        "related work experience",
        "experience to the job",
        "experience for this role",
        "experience in this field",
        "experience with",
        "worked with",
        "have you worked with",
        "previous experience",
        "recent experience",
        "powered industrial truck experience",
        "forklift experience",
        "do you have knowledge of",
        "do you have working knowledge",
        "do you possess experience",
        "have you used",
        "are you experienced with",
      ],
      excludeKeywords: [
        "years of experience",
        "how many years",
        "salary",
        "compensation",
        "trans experience",
        "lived experience",
      ],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("compensation_offer_factors", {
      aliases: [
        "factors bms should consider when creating a compensation offer",
        "any factors bms should consider",
        "factors should consider when creating a compensation offer",
        "not required to disclose salary or compensation history",
        "compensation offer",
        "compensation history",
      ],
      profilePaths: ["compensationOfferFactors"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("salary_comfortable", {
      aliases: [
        "comfortable with the following salary",
        "comfortable with the following salary for your work term",
        "are you comfortable with the following salary",
      ],
      profilePaths: ["salaryFlexible"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("salary_expectation", {
      aliases: [
        "salary",
        "base salary",
        "base salary expectations",
        "salary expectation",
        "salary expectations",
        "compensation",
        "compensation expectation",
        "total compensation",
        "pay expectation",
        "desired pay",
        "hourly expectation",
        "hourly expectations",
        "hourly expectations for the position",
        "hourly pay expectation",
        "hourly pay expectation for this position",
        "hourly rate",
        "expected hourly rate",
        "hourly wage expectation",
        "wage expectation",
        "wage expectations",
      ],
      excludeKeywords: [
        "compensation history",
        "compensation offer",
        "creating a compensation offer",
        "factors bms should consider",
        "not required to disclose salary or compensation history",
      ],
      profilePaths: [
        "hourlyPayExpectation",
        "salaryExpectation",
        "salaryExpectationRange",
      ],
      defaultValue: "90,000 - 105,000",
    }),
    entry("english_language_proficiency", {
      aliases: [
        "language skills",
        "best describes your language skills",
        "fluent means able to communicate",
        "read write and speak in both languages",
        "english level",
        "level of english",
        "nível de inglês",
        "nivel de ingles",
        "qual e o seu nivel de ingles",
        "qual é o seu nível de inglês",
      ],
      profilePaths: [
        "languageSkillsStatement",
        "englishProficiency",
        "englishLevel",
      ],
      defaultValue: "I am fluent in English only",
      answerType: "option",
      optionAliases: {
        "I am fluent in English only": [
          "I am fluent in English only",
          "Fluent in English only",
          "English only",
          "Fluent",
          "Native",
          "Advanced",
        ],
        Fluente: ["Fluent", "Native", "Nativo/Native", "Advanced", "Avançado"],
      },
    }),
    entry("portuguese_language_proficiency", {
      aliases: [
        "portuguese level",
        "level of portuguese",
        "nivel de portugues",
        "nível de português",
        "nivel de portugués",
        "cuál es tu nivel de portugués",
        "qual é o seu nível de português",
      ],
      profilePaths: ["portugueseProficiency", "portugueseLevel"],
      defaultValue: "Básico/Basic",
      answerType: "option",
      optionAliases: {
        "Básico/Basic": ["Basic", "Básico", "Basico"],
      },
    }),
    entry("language_yes_no", {
      aliases: [
        "do you speak english",
        "can you speak english",
        "are you fluent in english",
        "do you speak french",
        "can you speak french",
        "are you fluent in french",
        "do you speak spanish",
        "can you speak spanish",
        "are you fluent in spanish",
        "read write and speak english",
        "read write and speak french",
        "read write and speak spanish",
      ],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("disclosure_neutral", {
      aliases: [
        "gender",
        "disability",
        "veteran",
        "ethno-racial",
        "ethno racial",
        "racial identity",
        "racialized",
        "ethno-racial identity",
        "visible minority",
        "visible minority based on the definition",
        "member of a visible minority",
        "member of an visible minority",
        "indigenous",
        "aboriginal people",
        "member of an aboriginal people",
        "member of aboriginal people",
        "self-identify",
        "i do not want to answer",
        "diversity",
        "sexual orientation",
      ],
      profilePaths: [
        "disclosureGender",
        "disclosureDisability",
        "disclosureVeteranStatus",
        "disclosureVisibleMinority",
        "disclosureIndigenousIdentity",
        "disclosureLgbqIdentity",
        "disclosureTransExperience",
      ],
      defaultValue: "I choose not to disclose",
      answerType: "non_disclosure",
    }),
  ];

  root.fieldCatalog = {
    entries: QUESTION_CATALOG,
    nonDisclosureAliases: NON_DISCLOSURE_ALIASES,
  };
})();
