(function () {
  var root = (window.__huntV2 = window.__huntV2 || {});

  var NON_DISCLOSURE_ALIASES = [
    "I choose not to disclose",
    "Choose not to disclose",
    "Prefer not to disclose",
    "I prefer not to answer",
    "Prefer not to answer",
    "Prefer not to respond",
    "Prefer not to respond (Canada)",
    "I prefer not to identify",
    "Prefer not to identify",
    "I do not want to answer",
    "I don't want to answer",
    "I do not wish to answer",
    "I DO NOT WISH TO ANSWER",
    "I don't wish to answer",
    "I DON'T WISH TO ANSWER",
    "Don't wish to answer",
    "I do not wish to answer.",
    "I do not wish to answer (United States of America)",
    "I do not wish to answer. (United States of America)",
    "I don't wish to answer (United States of America)",
    "Decline to State",
    "Do not wish to disclose",
    "I do not wish to self-identify",
    "Decline to answer",
    "Not disclosed",
    "Undisclosed",
    "Undisclosed (United States of America)",
    "Not declared",
    "Not Declared",
    "Not specified",
    "Not Specified",
    "Not specified (United States of America)",
    "Not Specified (United States of America)",
    "None of these",
    "None of the above",
    "I do not declare",
    "Do not declare",
  ];

  function entry(id, config) {
    return Object.assign(
      {
        id: id,
        exactLabels: [],
        aliases: [],
        includeKeywords: [],
        excludeKeywords: [],
        profilePaths: [],
        defaultValue: "",
        answerType: "text",
        optionAliases: {},
      },
      config || {},
    );
  }

  var QUESTION_CATALOG = [
    entry("first_name", {
      aliases: ["first name", "given name", "legal first name"],
      profilePaths: ["firstName"],
    }),
    entry("middle_name", {
      aliases: ["middle name", "legal middle name"],
      profilePaths: ["middleName"],
    }),
    entry("last_name", {
      aliases: ["last name", "surname", "family name", "legal last name"],
      profilePaths: ["lastName"],
    }),
    entry("name_prefix", {
      aliases: ["prefix", "name prefix", "legal name prefix", "title"],
      defaultValue: "Not Mapped",
      answerType: "option",
      optionAliases: {
        "Not Mapped": ["Not Mapped", "None", "No Prefix"],
      },
    }),
    entry("full_name", {
      exactLabels: ["name"],
      aliases: [
        "full name",
        "legal name",
        "candidate name",
        "applicant name",
        "enter your name",
        "please enter your name",
      ],
      profilePaths: ["fullName"],
    }),
    entry("email", {
      aliases: ["email", "e-mail", "email address", "contact email"],
      profilePaths: ["email"],
    }),
    entry("account_password", {
      aliases: [
        "password",
        "new password",
        "verify new password",
        "confirm password",
      ],
      excludeKeywords: [
        "current password",
        "old password",
        "existing password",
        "temporary password",
      ],
      profilePaths: ["accountPassword"],
    }),
    entry("phone", {
      aliases: ["phone", "phone number", "mobile", "cell", "telephone"],
      profilePaths: ["phone"],
    }),
    entry("phone_device_type", {
      aliases: ["phone device type", "phone type", "device type"],
      profilePaths: ["phoneDeviceType"],
      defaultValue: "Mobile",
    }),
    entry("phone_country_code", {
      aliases: [
        "phone country code",
        "country phone code",
        "country / territory phone code",
      ],
      profilePaths: ["phoneCountryCode"],
      defaultValue: "Canada (+1)",
      optionAliases: { "Canada (+1)": ["Canada", "+1", "CA +1"] },
    }),
    entry("workday_system_usage", {
      aliases: [
        "use or work on the workday system",
        "work on the workday system",
        "current job do you use or work",
      ],
      excludeKeywords: ["describe your interactions", "describe interactions"],
      defaultValue: "No, I do not use the Workday system in my current job",
    }),
    entry("truthful_application_acknowledgement", {
      aliases: [
        "please enter yes if you acknowledge",
        "acknowledge that you have read",
        "acknowledge that you understand",
        "truthfully and accurately",
        "information is true",
      ],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("identity_verification_upon_hire", {
      aliases: [
        "provide verification of your identity upon hire",
        "provide verification of your identify upon hire",
        "provide proof of identity upon hire",
        "verify your identity upon hire",
        "identity verification upon hire",
      ],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("relocation_willingness", {
      aliases: [
        "are you willing to relocate",
        "are you willing to relocate if needed",
      ],
      profilePaths: ["willingToRelocate"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("relocation_consideration", {
      aliases: ["would you consider relocating for this role"],
      profilePaths: ["relocationPreference", "willingToRelocate"],
      defaultValue: "I am local to where the job is posted",
    }),
    entry("non_compete_restriction", {
      aliases: [
        "non-compete or non-solicitation restrictions",
        "non compete or non solicitation restrictions",
        "contractual restrictions on your ability to work",
        "contractual restrictions exist",
        "bound by any non-solicitation agreements",
        "non-solicitation agreements which would restrict your ability",
        "restrict your ability to prospect for business",
        "bound by a continuing confidentiality or patent agreement",
        "agreements that contain a restrictive covenant",
        "non-compete, non-solicitation or non-disclosure",
        "restrictive agreement",
        "restrictive agreements",
        "subject to any restrictive agreement",
        "restrict your ability to work",
        "limit your ability to work",
        "restrictive covenant",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("current_company_employee", {
      aliases: [
        "do you currently work at",
        "currently work at cvs health",
        "current employee of cvs health",
      ],
      profilePaths: ["currentEmployers"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("government_exclusion_or_debarment", {
      aliases: [
        "excluded, debarred, suspended",
        "excluded debarred suspended",
        "ineligible from participation in any federal or state healthcare program",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("foreign_pharmacist_licensure_hours", {
      aliases: [
        "pharmacist from another country needing hours towards licensure",
        "another country needing hours towards licensure",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("sms_communication_authorization", {
      aliases: [
        "authorize cvs health to communicate with me via text",
        "communicate with me via text",
        "standard message rates may apply",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("proof_of_us_work_authorization", {
      aliases: [
        "provide proof that you are legally able to work in the united states",
        "legally able to work in the united states",
        "verify identity and eligibility to work in the united states",
      ],
      profilePaths: ["workAuthorized"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("government_official", {
      aliases: [
        "are you or have you been within the last 12 months a government official",
        "are you a government official",
        "have you been a government official",
        "government official",
        "current or former employee of the united states government",
        "former employee of the united states government",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("export_control_restricted_region", {
      aliases: [
        "export control laws",
        "current citizen, national or resident",
        "current citizen national or resident",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("related_current_employee", {
      aliases: [
        "related to a current workday employee",
        "related to a current employee",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("related_customer_or_government_official", {
      aliases: [
        "direct business interactions with workday",
        "related to an employee of a customer",
        "related to a government official",
        "immediate family members government officials",
        "family members government officials",
        "family member government official",
        "employee of any government department agency",
        "organization owned fully or partially by government",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("gender_disclosure_neutral", {
      aliases: [
        "please select your gender",
        "gender identity",
        "gender expression",
      ],
      defaultValue: "Not Declared",
      answerType: "non_disclosure",
      optionAliases: {
        "Not Declared": [
          "Not Declared",
          "I choose not to disclose",
          "I do not want to answer",
          "I do not wish to answer",
          "Prefer not to answer",
        ],
      },
    }),
    entry("ethnicity_disclosure_neutral", {
      aliases: [
        "ethnicity which most accurately describes",
        "what is your ethnicity",
        "ethnicity",
        "ethnicities",
        "ethnicity(ies)",
        "please select the ethnicity",
        "personalinfoperson--ethnicities",
        "ethno-racial identity",
        "ethno racial identity",
        "ethno-racial identities",
        "ethno racial identities",
        "race/ethnicity",
        "race ethnicity",
      ],
      defaultValue: "I decline to disclose",
      answerType: "non_disclosure",
      optionAliases: {
        "I decline to disclose": [
          "I decline to disclose",
          "I choose not to disclose",
          "I do not want to answer",
          "I do not want to answer (United States of America)",
          "I do not wish to answer",
          "I do not wish to answer.",
          "I do not wish to answer (United States of America)",
          "I do not wish to answer. (United States of America)",
          "Decline to State",
          "Decline to State (United States of America)",
          "Declined to State",
          "Declined to State (United States of America)",
          "Declined to Identify",
          "Declined to Identify (United States of America)",
          "Prefer not to answer",
          "Prefer not to respond",
          "Prefer not to respond (Canada)",
          "Not Specified",
          "Not Specified (United States of America)",
          "Not Declared",
        ],
      },
    }),
    entry("veteran_disclosure_neutral", {
      aliases: [
        "please provide your current veteran status",
        "current veteran status",
        "are you a veteran",
        "veteran status",
        "protected veteran",
      ],
      defaultValue: "I CHOOSE NOT TO SELF-IDENTIFY",
      answerType: "non_disclosure",
      optionAliases: {
        "I CHOOSE NOT TO SELF-IDENTIFY": [
          "I CHOOSE NOT TO SELF-IDENTIFY",
          "I DO NOT WISH TO SELF-IDENTIFY",
          "I DO NOT WISH TO SELF IDENTIFY",
          "I DON'T WISH TO ANSWER",
          "I DO NOT WISH TO ANSWER",
          "I choose not to disclose",
          "Not Declared",
        ],
      },
    }),
    entry("city", {
      aliases: ["city", "current city", "home city"],
      profilePaths: ["city"],
    }),
    entry("province", {
      aliases: ["province", "state", "province territory", "region"],
      profilePaths: ["province"],
      optionAliases: {
        Alberta: ["AB"],
        "British Columbia": ["BC", "B.C."],
        Manitoba: ["MB"],
        "New Brunswick": ["NB"],
        "Newfoundland and Labrador": ["NL"],
        "Northwest Territories": ["NT"],
        "Nova Scotia": ["NS"],
        Nunavut: ["NU"],
        Ontario: ["ON"],
        "Prince Edward Island": ["PE", "PEI"],
        Quebec: ["QC"],
        Saskatchewan: ["SK"],
        Yukon: ["YT"],
      },
    }),
    entry("country", {
      aliases: [
        "country",
        "current country",
        "country territory",
        "country region",
      ],
      profilePaths: ["country"],
      defaultValue: "Canada",
    }),
    entry("location", {
      aliases: ["location", "current location", "where are you located"],
      profilePaths: ["location"],
    }),
    entry("address_line_1", {
      aliases: ["address line 1", "street address", "address"],
      profilePaths: ["addressLine1"],
    }),
    entry("address_line_2", {
      aliases: ["address line 2", "apartment", "unit"],
      profilePaths: ["addressLine2"],
    }),
    entry("postal_code", {
      aliases: ["postal code", "zip code"],
      profilePaths: ["postalCode"],
    }),
    entry("linkedin", {
      aliases: ["linkedin", "linkedin url", "linkedin profile"],
      profilePaths: ["linkedinUrl"],
    }),
    entry("github", {
      aliases: ["github", "github url", "github profile"],
      profilePaths: ["githubUrl"],
    }),
    entry("website", {
      aliases: ["website", "portfolio", "personal site"],
      profilePaths: ["websiteUrl"],
    }),
    entry("technical_skills", {
      aliases: [
        "type to add skills",
        "add skills",
        "skills describe your knowledge",
        "skills",
      ],
      profilePaths: ["skills", "skillList", "technicalSkills"],
    }),
    entry("resume_upload", {
      aliases: [
        "resume",
        "cv",
        "resume/cv",
        "upload a file",
        "select files",
        "select file",
        "drop files",
      ],
      defaultValue: "resume_upload",
      answerType: "file",
    }),
    entry("application_source", {
      aliases: ["how did you hear", "source", "application source"],
      profilePaths: [
        "applicationSourceCategory",
        "applicationSource",
        "applicationSourceDetail",
      ],
      defaultValue: "LinkedIn",
    }),
    entry("terms_acceptance", {
      aliases: [
        "terms and conditions",
        "accept terms",
        "accept terms and agreements",
        "read and consent",
        "consent to the terms",
        "agree with the terms",
        "agree with the terms and conditions",
        "career privacy notice",
        "privacy notice",
        "agree to the above career privacy notice",
        "candidate privacy statement",
        "candidate acknowledgment",
        "candidate acknowledgement",
        "by continuing, you agree",
        "check the box to continue",
        "agree to creating this account",
        "creating this account",
        "create account checkbox",
        "createaccountcheckbox",
        "allow me to apply",
        "account to allow me to apply",
        "accepttermsandagreements",
        "non disclosure agreement",
        "non-disclosure agreement",
        "arbitration agreement",
        "mutual arbitration agreement",
      ],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("sms_application_contact_opt_out", {
      aliases: [
        "reach out to me via sms",
        "sms regarding my application",
        "sms regarding my application and candidate experience",
        "message and data rates may apply",
        "i can opt-out at any time",
      ],
      defaultValue: "Opt-Out",
      optionAliases: {
        "Opt-Out": [
          "Opt-Out",
          "Opt Out",
          "OptOut",
          "No, I do not wish to receive SMS/Text messages",
          "No, I do not wish to receive SMS messages",
          "No, I do not wish to receive text messages",
        ],
      },
    }),
    entry("preferred_communication_channel", {
      aliases: [
        "preferred communication channel",
        "please select your preferred communication channel",
        "preferred method of communication",
        "preferred method of communication should we want to contact you",
      ],
      profilePaths: ["preferredCommunicationChannel"],
      defaultValue: "Email",
      answerType: "option",
      optionAliases: {
        Email: ["E-mail", "Email Address", "Personal Email", "Work Email"],
      },
    }),
    entry("aedt_processing_opt_out_request", {
      aliases: [
        "request to opt-out of the use of an aedts",
        "request to opt out of the use of an aedts",
        "opt-out of the use of an aedts in the recruitment process",
        "opt out of the use of an aedts in the recruitment process",
      ],
      profilePaths: ["automatedDecisionToolOptOut"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("automated_ai_processing_opt_out", {
      aliases: [
        "automated tools such as ai",
        "support review of your application",
        "match you with relevant existing and future open roles",
        "prefer not to have your application processed by these tools",
        "opting out will not impact your eligibility",
      ],
      defaultValue: "Opt-Out",
      optionAliases: {
        "Opt-Out": ["Opt-Out", "Opt Out", "OptOut"],
      },
    }),
    entry("current_date", {
      aliases: [
        "today's date",
        "todays date",
        "enter today's date",
        "enter todays date",
        "please enter today's date",
        "please enter todays date",
        "date signed",
        "date signed on",
        "signed on",
      ],
      excludeKeywords: [
        "18 years",
        "years of age",
        "years old",
        "age or older",
      ],
      defaultValue: "today",
    }),
    entry("has_bachelors_degree", {
      aliases: [
        "do you have a bachelor's degree",
        "do you have a bachelors degree",
        "have a bachelor's degree",
        "have a bachelors degree",
      ],
      profilePaths: ["highestEducation", "degreeLevel"],
      defaultValue: false,
      answerType: "education_level_yes_no",
      expectedEducationLevel: "bachelors",
    }),
    entry("work_authorized", {
      aliases: [
        "authorized to work",
        "able to legally work",
        "eligible to work",
        "entitled to work",
        "legally entitled to work",
        "legally allowed to work",
        "legally authorized",
        "legally permitted to work",
        "permitted to work",
        "legal right to work",
        "right to work in the country",
        "work authorization",
      ],
      excludeKeywords: ["sponsor", "sponsorship"],
      profilePaths: ["workAuthorized"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("sponsorship_required", {
      aliases: [
        "sponsor",
        "sponsorship",
        "require intel to sponsor",
        "require intel to sponsor a visa petition",
        "require employer immigration sponsorship",
        "require employer immigration sponsorship now or in the future",
        "require sponsorship now or in the future",
        "will you in the future require",
        "visa support",
        "visa petition",
        "employer-provided visa sponsorship",
        "immigration support",
      ],
      profilePaths: ["sponsorshipRequired"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("open_work_permit", {
      aliases: [
        "currently on an open work permit",
        "on an open work permit",
        "open work permit",
      ],
      profilePaths: ["openWorkPermit"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("canadian_citizenship_status", {
      aliases: [
        "canadian citizenship status",
        "provide your canadian citizenship status",
        "citizenship status to assist us",
      ],
      excludeKeywords: [
        "sponsor",
        "sponsorship",
        "visa",
        "visa petition",
        "work authorization application",
      ],
      profilePaths: ["canadianCitizenOrPermanentResident"],
      defaultValue: "Citizen (Canada)",
    }),
    entry("sanctioned_country_citizenship", {
      aliases: [
        "please indicate which if any where you are a citizen",
        "indicate which if any where you are a citizen",
        "which if any where you are a citizen",
        "where you are a citizen",
        "cuba syria north korea iran sudan none of these",
      ],
      defaultValue: "None of these",
      answerType: "option",
      optionAliases: {
        "None of these": ["None of these", "None"],
      },
    }),
    entry("secondary_citizenship", {
      aliases: [
        "secondary citizenship",
        "secondary country of citizenship",
        "second citizenship",
        "second country of citizenship",
        "additional citizenship",
        "additional country of citizenship",
        "other citizenship",
        "other country of citizenship",
        "dual citizenship",
      ],
      profilePaths: ["secondaryCitizenship", "secondCitizenship"],
      defaultValue: "None of these",
      answerType: "option",
      optionAliases: {
        "None of these": NON_DISCLOSURE_ALIASES.concat([
          "None",
          "No",
          "No Secondary Citizenship",
          "No secondary citizenship",
          "No other citizenship",
          "No additional citizenship",
        ]),
      },
    }),
    entry("citizenship", {
      aliases: [
        "country of citizenship",
        "citizenship country",
        "citizenship",
        "nationality",
        "country of nationality",
      ],
      excludeKeywords: [
        "sponsor",
        "sponsorship",
        "visa",
        "visa petition",
        "work authorization application",
        "secondary",
        "second",
        "additional",
        "other",
        "dual",
        "which if any where you are a citizen",
      ],
      profilePaths: ["citizenship", "primaryCitizenship", "country"],
      defaultValue: "Canada",
      answerType: "option",
      optionAliases: {
        Canada: ["Canada", "Citizen (Canada)", "Canadian", "Canada citizen"],
      },
    }),
    entry("canadian_citizen_pr", {
      aliases: ["canadian citizen", "permanent resident"],
      excludeKeywords: [
        "sponsor",
        "sponsorship",
        "visa",
        "visa petition",
        "work authorization application",
      ],
      profilePaths: ["canadianCitizenOrPermanentResident"],
      answerType: "yes_no",
    }),
    entry("previous_employer", {
      aliases: [
        "previously worked",
        "previously employed",
        "previously been employed",
        "previously employed by",
        "previously or are you currently engaged",
        "employed in the past",
        "employed by",
        "have you been employed by",
        "ever worked for",
        "worked for",
        "worked at",
        "former employee",
        "contractor consultant former employee",
        "access to bms systems",
        "employee or as a contractor",
        "employee or contractor",
        "current employee",
        "current atco employee",
      ],
      profilePaths: ["previousEmployers"],
      defaultValue: false,
      answerType: "exact_previous_employer",
    }),
    entry("previous_application", {
      aliases: [
        "have you ever applied for employment with this company",
        "applied for employment with this company",
        "previously applied",
        "applied previously",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("prior_termination_or_resignation", {
      aliases: [
        "have you ever been terminated",
        "ever been terminated",
        "terminated or asked to resign",
        "asked to resign from employment",
        "asked to resign",
        "discharged from employment",
        "involuntarily terminated",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("referral_or_family", {
      aliases: [
        "referral",
        "know anyone",
        "family member",
        "relative",
        "domestic partner",
      ],
      profilePaths: ["familyMemberAtCompany"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("background_check_consent", {
      aliases: [
        "willing to complete a background",
        "willing to complete a background security check",
        "willing to complete a criminal background check",
        "able to clear a criminal background check",
        "complete a background security check",
        "complete a background check",
        "clear a criminal background check",
        "criminal record and references",
        "reference check",
        "background screening",
        "identity verification",
        "drug testing",
        "drug test",
        "pre-employment drug screening",
        "understand and consent to background",
      ],
      excludeKeywords: ["convicted", "criminal offence", "criminal offense"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("legal_age_industry_eligibility", {
      aliases: [
        "legal age to work",
        "of legal age to work",
        "legal age to work in the cannabis",
        "legal age to work in the cannabis liquor industry",
        "legal age to work in the liquor industry",
      ],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("essential_functions", {
      aliases: [
        "able to perform the essential functions",
        "perform the essential functions",
        "essential functions of the position",
        "with or without reasonable accommodation",
      ],
      profilePaths: ["canPerformEssentialFunctions"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("reliable_transportation", {
      aliases: [
        "valid driver's license or have reliable transportation",
        "valid driver’s license or have reliable transportation",
        "drivers license or have reliable transportation",
        "driver's license or have reliable transportation",
        "reliable transportation to report to work",
        "have reliable transportation",
      ],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("union_membership", {
      aliases: [
        "member of cewa",
        "cewa",
        "union member",
        "member of a union",
        "member of union",
      ],
      profilePaths: ["cewaMember", "unionMembership"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("degree_level", {
      aliases: ["degree level", "level of education", "education level"],
      profilePaths: ["degreeLevel"],
      optionAliases: {
        "Bachelor's Degree": ["Bachelor's", "Bachelors", "Bachelor", "University"],
        "Graduate School": ["Graduate School", "MBA", "PHD", "PhD", "Master"],
        Bachelors: ["Bachelor's", "Bachelor's Degree", "Bachelor"],
      },
    }),
    entry("highest_education", {
      aliases: [
        "highest education",
        "highest degree attained",
        "highest level of education",
        "highest level of completed education",
      ],
      profilePaths: ["highestEducation", "degreeLevel"],
      optionAliases: {
        "Bachelor's Degree": ["Bachelor's", "Bachelors", "Bachelor", "University"],
        "Graduate School": ["Graduate School", "MBA", "PHD", "PhD", "Master"],
        Bachelors: ["Bachelor's", "Bachelor's Degree", "Bachelor"],
      },
    }),
    entry("microsoft_office_proficiency", {
      aliases: [
        "microsoft office proficiency",
        "level of computer proficiency in microsoft office",
        "computer proficiency in microsoft office",
      ],
      profilePaths: ["microsoftOfficeProficiency", "officeProficiency"],
      defaultValue: "Expert",
      optionAliases: {
        Expert: ["Expert", "Advanced", "Fluent", "Native", "Excellent"],
      },
    }),
    entry("highest_proficiency", {
      aliases: [
        "proficiency",
        "level of proficiency",
        "proficiency level",
      ],
      profilePaths: ["proficiencyLevel"],
      defaultValue: "Expert",
      optionAliases: {
        Expert: ["Expert", "Advanced", "Fluent", "Native", "Excellent"],
      },
    }),
    entry("travel_availability", {
      aliases: [
        "travel is required",
        "what is your availability",
        "travel availability",
        "availability for travel",
      ],
      profilePaths: ["travelAvailability"],
      defaultValue: "highest",
      answerType: "travel_availability",
    }),
    entry("outside_conflict_activities", {
      aliases: [
        "outside activities",
        "trade groups or board memberships",
        "competitive to or in competition with",
        "conflicting outside activities",
        "possible conflicting outside activities",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("computer_programs", {
      aliases: [
        "what other computer programs have you worked in",
        "other computer programs",
        "computer programs have you worked in",
      ],
      profilePaths: ["computerPrograms", "skills", "skillList", "technicalSkills"],
      defaultValue: "",
    }),
    entry("expected_graduation_year", {
      aliases: ["graduation year", "expected graduation"],
      profilePaths: ["expectedGraduationYear"],
    }),
    entry("desired_start_date", {
      aliases: [
        "desired start date",
        "available start date",
        "available to start",
        "available to start work",
        "date are you available to start work",
        "earliest date you can start",
        "if hired what is the earliest date you can start",
        "earliest availability to start this new position",
        "when is your earliest availability to start this new position",
        "earliest date that you could start work",
        "earliest date you could start work",
        "could start work",
        "accept a job offer",
        "start work date",
      ],
      profilePaths: ["desiredStartDate"],
      defaultValue: "today",
    }),
    entry("shift_availability", {
      aliases: [
        "shift availability",
        "what is your shift availability",
        "select all that apply",
      ],
      profilePaths: ["shiftAvailability"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("full_time_part_time_preference", {
      aliases: [
        "interested in a full time or part time position",
        "full time or part time position",
      ],
      profilePaths: ["employmentTypePreference"],
      defaultValue: "Full Time",
      answerType: "option",
      optionAliases: {
        "Full Time": ["Full Time", "Full-Time"],
      },
    }),
    entry("military_spouse_partner", {
      aliases: [
        "spouse or partner of someone who serves",
        "spouse or partner of someone who served",
        "serves/served in the u.s. military",
      ],
      profilePaths: ["militarySpouseOrPartner"],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("age_at_least_18", {
      aliases: [
        "as of today's date are you 18 years of age or older",
        "as of todays date are you 18 years of age or older",
        "are you age 18 or over",
        "age 18 or over",
        "are you 18 years of age or older",
        "18 years of age or older",
        "are you 18 years or older",
        "18 years or older",
        "are you at least 18 years old",
        "at least 18 years old",
        "are you at least 18 years of age",
        "at least 18 years of age",
      ],
      profilePaths: ["atLeast18"],
      defaultValue: true,
      answerType: "yes_no",
    }),
    entry("professional_license_discipline", {
      aliases: [
        "disciplinary action taken on your professional license",
        "disciplinary action taken on your professional license, certification, or credentials",
        "anticipate receiving any disciplinary action",
      ],
      defaultValue: false,
      answerType: "yes_no",
    }),
    entry("hourly_pay_expectation", {
      aliases: [
        "hourly pay expectation",
        "hourly pay expectation for this position",
      ],
      profilePaths: ["hourlyPayExpectation"],
      defaultValue: "Decline to Answer",
      answerType: "option",
      optionAliases: {
        "Decline to Answer": ["Decline to Answer", "Prefer not to answer"],
      },
    }),
    entry("salary_expectation", {
      aliases: [
        "salary",
        "base salary",
        "base salary expectations",
        "salary expectation",
        "salary expectations",
        "compensation",
        "compensation expectation",
        "total compensation",
        "pay expectation",
        "desired pay",
      ],
      profilePaths: ["salaryExpectationRange", "salaryExpectation"],
      defaultValue: "90,000 - 105,000",
    }),
    entry("english_language_proficiency", {
      aliases: [
        "language skills",
        "best describes your language skills",
        "fluent means able to communicate",
        "read write and speak in both languages",
        "english level",
        "level of english",
        "nível de inglês",
        "nivel de ingles",
        "qual e o seu nivel de ingles",
        "qual é o seu nível de inglês",
      ],
      profilePaths: [
        "languageSkillsStatement",
        "englishProficiency",
        "englishLevel",
      ],
      defaultValue: "I am fluent in English only",
      answerType: "option",
      optionAliases: {
        "I am fluent in English only": [
          "I am fluent in English only",
          "Fluent in English only",
          "English only",
          "Fluent",
          "Native",
          "Advanced",
        ],
        Fluente: ["Fluent", "Native", "Nativo/Native", "Advanced", "Avançado"],
      },
    }),
    entry("portuguese_language_proficiency", {
      aliases: [
        "portuguese level",
        "level of portuguese",
        "nivel de portugues",
        "nível de português",
        "nivel de portugués",
        "cuál es tu nivel de portugués",
        "qual é o seu nível de português",
      ],
      profilePaths: ["portugueseProficiency", "portugueseLevel"],
      defaultValue: "Básico/Basic",
      answerType: "option",
      optionAliases: {
        "Básico/Basic": ["Basic", "Básico", "Basico"],
      },
    }),
    entry("disclosure_neutral", {
      aliases: [
        "gender",
        "disability",
        "veteran",
        "ethno-racial",
        "ethno racial",
        "racial identity",
        "racialized",
        "ethno-racial identity",
        "visible minority",
        "visible minority based on the definition",
        "member of a visible minority",
        "member of an visible minority",
        "indigenous",
        "aboriginal people",
        "member of an aboriginal people",
        "member of aboriginal people",
        "self-identify",
        "i do not want to answer",
        "diversity",
        "sexual orientation",
      ],
      profilePaths: [
        "disclosureGender",
        "disclosureDisability",
        "disclosureVeteranStatus",
        "disclosureVisibleMinority",
        "disclosureIndigenousIdentity",
        "disclosureLgbqIdentity",
        "disclosureTransExperience",
      ],
      defaultValue: "I choose not to disclose",
      answerType: "non_disclosure",
      optionAliases: { "I choose not to disclose": NON_DISCLOSURE_ALIASES },
    }),
  ];

  root.fieldCatalog = {
    entries: QUESTION_CATALOG,
    nonDisclosureAliases: NON_DISCLOSURE_ALIASES,
  };
})();
