"""Strict recognition for opaque identifiers generated by the C3 control plane."""

from __future__ import annotations

import re
from typing import Any

_TRUSTED_EVENT_ID_RE = re.compile(r"(?i)^evt-(?:terminal-)?[0-9a-f]{32}$")
_TRUSTED_OPERATION_ID_RE = re.compile(r"(?i)^op-[a-p]{32}$")
_TRUSTED_ARTIFACT_ID_RE = re.compile(r"(?i)^artifact_[0-9a-f]{32}$")
_TRUSTED_DIAGNOSIS_ID_RE = re.compile(
    r"(?i)^diagnosis-op-[a-p]{32}-(?:evt-(?:terminal-)?[0-9a-f]{32}|[0-9]+|none)$"
)
_TRUSTED_GENERATED_C3_ID_RE = re.compile(
    r"(?i)^(?:"
    r"evt-(?:terminal-)?[0-9a-f]{32}|"
    r"op-[a-p]{32}|"
    r"artifact_[0-9a-f]{32}|"
    r"diagnosis-op-[a-p]{32}-(?:evt-(?:terminal-)?[0-9a-f]{32}|[0-9]+|none)"
    r")$"
)
_TRUSTED_LEASE_ID_RE = re.compile(r"(?i)^lease_[0-9a-f]{12}$")
_TRUSTED_CDP_TARGET_ID_RE = re.compile(r"(?i)^[0-9a-f]{32}$")


def is_trusted_generated_c3_id(value: Any) -> bool:
    """Return true only for a complete identifier shape generated internally by C3."""

    return isinstance(value, str) and _TRUSTED_GENERATED_C3_ID_RE.fullmatch(value) is not None


_FIELD_ID_PATTERNS = {
    "artifactid": _TRUSTED_ARTIFACT_ID_RE,
    "artifactids": _TRUSTED_ARTIFACT_ID_RE,
    "authoritativeeventid": _TRUSTED_EVENT_ID_RE,
    "diagnosisid": _TRUSTED_DIAGNOSIS_ID_RE,
    "eventid": _TRUSTED_EVENT_ID_RE,
    "eventids": _TRUSTED_EVENT_ID_RE,
    "evidenceeventids": _TRUSTED_EVENT_ID_RE,
    "leaseid": _TRUSTED_LEASE_ID_RE,
    "operationid": _TRUSTED_OPERATION_ID_RE,
    "parentoperationid": _TRUSTED_OPERATION_ID_RE,
    "targetid": _TRUSTED_CDP_TARGET_ID_RE,
}


def _is_trusted_identifier_for_field(value: Any, field: str | None) -> bool:
    normalized = re.sub(r"[^a-z0-9]", "", str(field or "").lower())
    if not isinstance(value, str):
        return False
    pattern = _FIELD_ID_PATTERNS.get(normalized)
    return pattern is not None and pattern.fullmatch(value) is not None


def restore_trusted_generated_c3_ids(
    redacted: Any,
    original: Any,
    *,
    field: str | None = None,
) -> Any:
    """Restore strict generated IDs only when they occupy an identifier field."""

    if _is_trusted_identifier_for_field(original, field):
        return original
    if isinstance(original, dict) and isinstance(redacted, dict):
        return {
            key: restore_trusted_generated_c3_ids(value, original[key], field=key)
            if key in original
            else value
            for key, value in redacted.items()
        }
    if isinstance(original, list) and isinstance(redacted, list):
        return [
            restore_trusted_generated_c3_ids(value, original[index], field=field)
            if index < len(original)
            else value
            for index, value in enumerate(redacted)
        ]
    return redacted
