export const GENERIC_FIELD_RULES = {
  requiredIndicators: [
    "required",
    "mandatory",
    "must complete",
    "must be completed",
  ],
  resumePhrases: [
    "resume",
    "cv",
    "curriculum vitae",
    "upload resume",
    "attach resume",
    "resume upload",
  ],
  excludedPhrases: [
    "account name",
    "address line",
    "cover letter",
    "current company",
    "emergency contact",
    "file name",
    "postal code",
    "manager name",
    "password",
    "school name",
    "supervisor name",
    "team name",
    "username",
    "zip code",
  ],
  profileFields: [
    {
      key: "firstName",
      valueKey: "firstName",
      phrases: [
        "first name",
        "given name",
        "forename",
        "personal name",
        "preferred first name",
      ],
    },
    {
      key: "lastName",
      valueKey: "lastName",
      phrases: [
        "last name",
        "surname",
        "family name",
        "legal surname",
        "maiden name",
        "previous last name",
      ],
    },
    {
      key: "preferredName",
      valueKey: "firstName",
      phrases: ["preferred name", "chosen name", "known as", "nickname"],
    },
    {
      key: "fullName",
      valueKey: "fullName",
      phrases: [
        "full name",
        "legal name",
        "candidate name",
        "applicant name",
        "your name",
        "name as it appears",
      ],
    },
    {
      key: "email",
      valueKey: "email",
      phrases: [
        "email",
        "e-mail",
        "email address",
        "primary email",
        "contact email",
      ],
    },
    {
      key: "phone",
      valueKey: "phone",
      phrases: [
        "phone",
        "phone number",
        "mobile",
        "mobile number",
        "cell",
        "cell phone",
        "telephone",
        "primary phone",
      ],
    },
    {
      key: "location",
      valueKey: "location",
      phrases: ["location", "city", "current city", "home city"],
    },
    {
      key: "linkedinUrl",
      valueKey: "linkedinUrl",
      phrases: ["linkedin", "linkedin url", "linkedin profile"],
    },
    {
      key: "githubUrl",
      valueKey: "githubUrl",
      phrases: ["github", "github url", "github profile"],
    },
    {
      key: "websiteUrl",
      valueKey: "websiteUrl",
      phrases: [
        "website",
        "portfolio",
        "personal site",
        "personal website",
        "portfolio url",
      ],
    },
  ],
  jobContextFields: [
    {
      key: "jobTitle",
      valueKey: "title",
      phrases: [
        "job title",
        "role title",
        "position",
        "position title",
        "position applied for",
        "role applied for",
        "job applied for",
        "application role",
      ],
    },
    {
      key: "company",
      valueKey: "company",
      phrases: [
        "company",
        "company name",
        "employer",
        "employer name",
        "organization",
        "organization name",
      ],
    },
    {
      key: "jobUrl",
      valueKey: "jobUrl",
      phrases: [
        "job url",
        "job link",
        "posting url",
        "posting link",
        "job posting",
      ],
    },
    {
      key: "applyUrl",
      valueKey: "applyUrl",
      phrases: ["application url", "apply url", "application link"],
    },
  ],
};
