const fieldOwners = {
  producer: "F2",
  consumer: "F9",
  semanticOwner: "F5",
  answerOwner: "F6",
  dispatcher: "F7",
  sideEffectOwner: "F3",
  verifier: "F8",
  eventOwner: "F9",
  failureOwner: "F10",
} as const;

export const requiredFieldFlowCases = [
  {
    ...fieldOwners,
    fieldId: "s1-field-given-name",
    fieldLabel: "Given name",
    questionId: "s1-question-given-name",
    questionLabel: "Given name",
    options: [],
    behavior: "text",
    htmlControl: "input[type=text]",
    browserObservation: "textbox value",
    answerSource: "profile.given_name",
    mutation: "type text",
    readback: "textbox value",
  },
  {
    ...fieldOwners,
    fieldId: "s1-field-family-name",
    fieldLabel: "Family name",
    questionId: "s1-question-family-name",
    questionLabel: "Family name",
    options: [],
    behavior: "text",
    htmlControl: "input[type=text]",
    browserObservation: "textbox value",
    answerSource: "profile.family_name",
    mutation: "type text",
    readback: "textbox value",
  },
  {
    ...fieldOwners,
    fieldId: "s1-field-phone-number",
    fieldLabel: "Phone number",
    questionId: "s1-question-phone-number",
    questionLabel: "Phone number",
    options: [],
    behavior: "text",
    htmlControl: "input[type=tel]",
    browserObservation: "textbox value",
    answerSource: "profile.phone_number",
    mutation: "type text",
    readback: "textbox value",
  },
  {
    ...fieldOwners,
    fieldId: "s1-field-interest",
    fieldLabel: "Brief interest statement",
    questionId: "s1-question-configured-narrative",
    questionLabel: "Why are you interested in this role?",
    options: [],
    behavior: "textarea",
    htmlControl: "textarea",
    browserObservation: "textarea value",
    answerSource: "profile.configured_narrative",
    mutation: "type textarea",
    readback: "textarea value",
  },
  {
    ...fieldOwners,
    fieldId: "s1-field-work-authorization",
    fieldLabel: "Are you authorized to work in this location?",
    questionId: "s1-question-work-authorization",
    questionLabel: "Are you authorized to work in this location?",
    options: [
      {
        id: "s1-option-work-authorization-yes",
        label: "Yes",
        value: "yes",
      },
      {
        id: "s1-option-work-authorization-no",
        label: "No",
        value: "no",
      },
    ],
    behavior: "radio",
    htmlControl: "fieldset input[type=radio]",
    browserObservation: "radio group options and selected option",
    answerSource: "profile.work_authorization",
    mutation: "select one grouped radio option",
    readback: "selected radio option",
  },
  {
    ...fieldOwners,
    fieldId: "s1-field-age-requirement",
    fieldLabel: "I am at least 18 years of age.",
    questionId: "s1-question-age-requirement-met",
    questionLabel: "Are you at least 18 years of age?",
    options: [],
    behavior: "checkbox",
    htmlControl: "input[type=checkbox]",
    browserObservation: "checkbox checked state",
    answerSource: "profile.age_requirement_met",
    mutation: "set checked state",
    readback: "checkbox checked state",
  },
  {
    ...fieldOwners,
    fieldId: "s1-field-sponsorship",
    fieldLabel: "Will you require sponsorship?",
    questionId: "s1-question-sponsorship-required",
    questionLabel: "Will you require sponsorship?",
    options: [
      { id: "s1-option-sponsorship-yes", label: "Yes", value: "yes" },
      { id: "s1-option-sponsorship-no", label: "No", value: "no" },
    ],
    behavior: "select",
    htmlControl: "select",
    browserObservation: "select options and selected option",
    answerSource: "profile.sponsorship_required",
    mutation: "select native option",
    readback: "selected native option",
  },
  {
    ...fieldOwners,
    fieldId: "s1-field-country",
    fieldLabel: "Country",
    questionId: "s1-question-country",
    questionLabel: "Country",
    options: [
      {
        id: "s1-option-country-us",
        label: "United States",
        value: "US",
      },
      { id: "s1-option-country-ca", label: "Canada", value: "CA" },
    ],
    behavior: "listbox",
    htmlControl: "[role=listbox]",
    browserObservation: "listbox options and selected option",
    answerSource: "profile.country",
    mutation: "select listbox option",
    readback: "selected listbox option",
  },
  {
    ...fieldOwners,
    fieldId: "s1-field-start-date",
    fieldLabel: "Available start date",
    questionId: "s1-question-earliest-start-date",
    questionLabel: "Available start date",
    options: [],
    behavior: "date",
    htmlControl: "input[type=date]",
    browserObservation: "date value",
    answerSource: "profile.earliest_start_date",
    mutation: "set ISO date",
    readback: "date value",
  },
  {
    ...fieldOwners,
    fieldId: "s1-field-resume",
    fieldLabel: "Resume",
    questionId: "s1-question-resume",
    questionLabel: "Resume",
    options: [],
    behavior: "file_upload",
    htmlControl: "input[type=file]",
    browserObservation: "file input state",
    answerSource: "resolved resume artifact",
    mutation: "upload verified artifact copy",
    readback: "uploaded artifact digest",
  },
] as const;

const executionReportingOwners = {
  eventOwner: "F9",
  failureOwner: "F10",
} as const;

export const requiredExecutionFlowCases = [
  {
    ...executionReportingOwners,
    step: "mcp_start",
    producer: "External MCP Client",
    consumer: "F9",
    sideEffectOwner: "F9",
    verifier: "F9",
  },
  {
    ...executionReportingOwners,
    step: "fixture_start",
    producer: "F13",
    consumer: "F2",
    sideEffectOwner: "F2",
    verifier: "F2",
  },
  {
    ...executionReportingOwners,
    step: "fixture_reset",
    producer: "F13",
    consumer: "F2",
    sideEffectOwner: "F2",
    verifier: "F2",
  },
  {
    ...executionReportingOwners,
    step: "fixture_close",
    producer: "F13",
    consumer: "F2",
    sideEffectOwner: "F2",
    verifier: "F2",
  },
  {
    ...executionReportingOwners,
    step: "intake",
    producer: "F4",
    consumer: "F9",
    sideEffectOwner: "F4",
    verifier: "F4",
  },
  {
    ...executionReportingOwners,
    step: "resume",
    producer: "F4",
    consumer: "F9",
    sideEffectOwner: "F4",
    verifier: "F4",
  },
  {
    ...executionReportingOwners,
    step: "profile",
    producer: "F4",
    consumer: "F6",
    sideEffectOwner: "F4",
    verifier: "F4",
  },
  {
    ...executionReportingOwners,
    step: "observation",
    producer: "F3",
    consumer: "F5",
    sideEffectOwner: "F3",
    verifier: "F5",
  },
  {
    ...executionReportingOwners,
    step: "semantic_meaning",
    producer: "F5",
    consumer: "F9",
    sideEffectOwner: "F5",
    verifier: "F5",
  },
  {
    ...executionReportingOwners,
    step: "answer",
    producer: "F6",
    consumer: "F9",
    sideEffectOwner: "F6",
    verifier: "F6",
  },
  {
    ...executionReportingOwners,
    step: "mutation",
    producer: "F7",
    consumer: "F3",
    sideEffectOwner: "F3",
    verifier: "F8",
  },
  {
    ...executionReportingOwners,
    step: "readback",
    producer: "F3",
    consumer: "F8",
    sideEffectOwner: "F3",
    verifier: "F8",
  },
  {
    ...executionReportingOwners,
    step: "navigation",
    producer: "F8",
    consumer: "F3",
    sideEffectOwner: "F3",
    verifier: "F8",
  },
  {
    ...executionReportingOwners,
    step: "journey_state",
    producer: "F9",
    consumer: "F4",
    sideEffectOwner: "F4",
    verifier: "F4",
  },
  {
    ...executionReportingOwners,
    step: "events",
    producer: "F9",
    consumer: "F10",
    sideEffectOwner: "F10",
    verifier: "F10",
  },
  {
    ...executionReportingOwners,
    step: "failure",
    producer: "F9",
    consumer: "F10",
    sideEffectOwner: "F10",
    verifier: "F10",
  },
  {
    ...executionReportingOwners,
    step: "privacy",
    producer: "F9",
    consumer: "F11",
    sideEffectOwner: "F11",
    verifier: "F11",
  },
  {
    ...executionReportingOwners,
    step: "evidence",
    producer: "F9",
    consumer: "F11",
    sideEffectOwner: "F11",
    verifier: "F11",
  },
  {
    ...executionReportingOwners,
    step: "terminal_result",
    producer: "F9",
    consumer: "External MCP Client",
    sideEffectOwner: "F9",
    verifier: "F9",
  },
] as const;

export const requiredControlFlowCases = [
  {
    port: "McpJourneyApi",
    provider: "F9 MCP Facade",
    consumers: ["External MCP Client"],
    sideEffectOwner: "F9",
    verifier: "F9",
    eventOwner: "F9",
    failureOwner: "F10",
  },
  {
    port: "JourneyControl",
    provider: "F9 Orchestrator",
    consumers: ["F9 MCP Facade"],
    sideEffectOwner: "F9",
    verifier: "F9",
    eventOwner: "F9",
    failureOwner: "F10",
  },
  {
    port: "JourneyIntake",
    provider: "F4 Intake",
    consumers: ["F9 Orchestrator"],
    sideEffectOwner: "F4",
    verifier: "F4",
    eventOwner: "F9",
    failureOwner: "F10",
  },
  {
    port: "JourneyStateStore",
    provider: "F4 Journey State",
    consumers: ["F9 Orchestrator"],
    sideEffectOwner: "F4",
    verifier: "F4",
    eventOwner: "F9",
    failureOwner: "F10",
  },
  {
    port: "ProfileQuery",
    provider: "F4 Profile",
    consumers: ["F6 Answer Resolver"],
    sideEffectOwner: "F4",
    verifier: "F4",
    eventOwner: "F9",
    failureOwner: "F10",
  },
  {
    port: "EventSink",
    provider: "F10 Observability",
    consumers: ["F9 Orchestrator"],
    sideEffectOwner: "F10",
    verifier: "F10",
    eventOwner: "F9",
    failureOwner: "F10",
  },
  {
    port: "ProgressReader",
    provider: "F10 Observability",
    consumers: ["F9 MCP Facade"],
    sideEffectOwner: "F10",
    verifier: "F10",
    eventOwner: "F9",
    failureOwner: "F10",
  },
  {
    port: "FailureReporter",
    provider: "F10 Failure Reporter",
    consumers: ["F9 Orchestrator"],
    sideEffectOwner: "F10",
    verifier: "F10",
    eventOwner: "F9",
    failureOwner: "F10",
  },
  {
    port: "PrivacyGuard",
    provider: "F11 Privacy Guard",
    consumers: ["F9 MCP Facade"],
    sideEffectOwner: "F11",
    verifier: "F11",
    eventOwner: "F9",
    failureOwner: "F10",
  },
  {
    port: "SafetyGuard",
    provider: "F11 Safety Guard",
    consumers: ["F9 Orchestrator"],
    sideEffectOwner: "F11",
    verifier: "F11",
    eventOwner: "F9",
    failureOwner: "F10",
  },
  {
    port: "EvidenceStore",
    provider: "F11 Evidence Store",
    consumers: ["F9 Orchestrator", "F10 Failure Reporter"],
    sideEffectOwner: "F11",
    verifier: "F11",
    eventOwner: "F9",
    failureOwner: "F10",
  },
] as const;

export const contractDeltaDecisions = [
  {
    id: "structural-browser-controls",
    classification: "requirement",
    decision: "Preserve textarea, date, grouped-choice, option, and checked-state structure.",
  },
  {
    id: "verified-resume-artifact",
    classification: "requirement",
    decision: "Upload only the immutable artifact whose digest was verified.",
  },
  {
    id: "closed-provider-failures",
    classification: "requirement",
    decision: "Propagate closed provider failures with explicit ownership and retryability.",
  },
  {
    id: "immutable-admission",
    classification: "requirement",
    decision: "Admit exact-shape immutable snapshots before side effects.",
  },
  {
    id: "stateful-conformance",
    classification: "requirement",
    decision: "Exercise negative, replay, cancellation, concurrency, and cleanup scenarios.",
  },
  {
    id: "bounded-identity-classes",
    classification: "owner_decision",
    decision: "Validate upstream opaque handles, inject non-sensitive generated IDs, and close coordinate enums.",
  },
  {
    id: "request-lifecycle",
    classification: "owner_decision",
    decision: "Distinguish duplicate requests, changed-input replays, cancellation, uncertain mutation, retry, and terminalization.",
  },
  {
    id: "event-ownership",
    classification: "owner_decision",
    decision: "F9 emits value-free provider-attributed events; F10 validates, stores, and projects them.",
  },
  {
    id: "model-controller-deferred",
    classification: "owner_decision",
    decision: "Stage 1 has no ModelController port or source owner.",
  },
  {
    id: "fixture-browser-navigation",
    classification: "owner_decision",
    decision: "F2 exposes start, reset, and close; browser navigation changes fixture pages.",
  },
  {
    id: "acceptance-provider-fault-wrapper",
    classification: "owner_decision",
    decision: "The acceptance harness owns explicit provider-failure injection.",
  },
  {
    id: "same-process-state-reload",
    classification: "owner_decision",
    decision: "Stage 1 proves deterministic same-process store reload, not crash recovery.",
  },
  {
    id: "fixture-transition-port",
    classification: "rejected_prototype_invention",
    decision: "Reject direct FixtureTransition requests and results.",
  },
  {
    id: "fixture-provider-fault-wrapper",
    classification: "rejected_prototype_invention",
    decision: "Keep provider-fault injection in the acceptance harness, not F2.",
  },
  {
    id: "derived-personal-identifiers",
    classification: "rejected_prototype_invention",
    decision: "Never derive retained identifiers from applicant data, URLs, selectors, paths, or messages.",
  },
] as const;
