import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const columns = [
  "Value or capability",
  "Persisted form",
  "Resolver",
  "Allowed consumers",
  "Side-effect owner",
  "Retention",
  "Deletion trigger and owner",
  "Crash cleanup",
  "Fault owner",
  "Factual or error result",
  "Terminal status",
  "Retryability",
  "Wire version",
] as const;

type MatrixRow = Record<(typeof columns)[number], string>;

function parseTable(markdown: string, heading: string): MatrixRow[] {
  const normalized = markdown.replace(/\r\n?/g, "\n");
  const section = normalized
    .split(`## ${heading}\n`, 2)[1]
    ?.split("\n## ", 1)[0];
  assert.ok(section, `missing ${heading} section`);

  const lines = section
    .split("\n")
    .filter((line) => line.startsWith("| "));
  assert.ok(lines.length >= 2, `missing ${heading} table`);

  const header = cells(lines[0] ?? "");
  assert.deepEqual(header, columns);
  assert.deepEqual(
    cells(lines[1] ?? ""),
    columns.map(() => "---"),
  );

  return lines.slice(2).map((line) => {
    const values = cells(line);
    assert.equal(values.length, columns.length, `bad matrix row: ${line}`);
    return Object.fromEntries(
      columns.map((column, index) => [column, values[index] ?? ""]),
    ) as MatrixRow;
  });
}

function cells(line: string): string[] {
  return line
    .slice(2, -2)
    .split(" | ")
    .map((value) => value.trim());
}

function parseDispositionTable(markdown: string) {
  const normalized = markdown.replace(/\r\n?/g, "\n");
  const section = normalized
    .split("## Prototype dispositions\n", 2)[1]
    ?.split("\n## ", 1)[0];
  assert.ok(section, "missing Prototype dispositions section");
  return [...section.matchAll(/^\| `([^`]+)` \| `([^`]+)` \| (.+) \|$/gm)].map(
    ([, artifact, disposition, reason]) => ({ artifact, disposition, reason }),
  );
}

const expectedRows: readonly MatrixRow[] = [
  {
    "Value or capability": "runtime root",
    "Persisted form": "Current-user-only directory outside the repository",
    Resolver: "Real-run preflight",
    "Allowed consumers": "F3 persistent browser; F9 live coordinator; recovery checkpoint store",
    "Side-effect owner": "Named runtime operator",
    Retention: "Approved active journey plus 24-hour crash-recovery lease",
    "Deletion trigger and owner": "Journey terminal or lease expiry; runner first, named runtime operator fallback",
    "Crash cleanup": "Delete stale, partial, ambiguous, or mismatched contents before a fresh start",
    "Fault owner": "Owner of the failing runtime resource",
    "Factual or error result": "runtime_root_invalid; runtime_root_cleanup_failed",
    "Terminal status": "failed; acceptance blocked",
    Retryability: "false",
    "Wire version": "live-internal v1; never MCP",
  },
  {
    "Value or capability": "secrets root",
    "Persisted form": "Current-user-only directory outside the repository",
    Resolver: "windows-dpapi-current-user-v1 SecretStore",
    "Allowed consumers": "SecretStore only",
    "Side-effect owner": "Named secret custodian",
    Retention: "Only approved DPAPI ciphertext records within their authorization window",
    "Deletion trigger and owner": "Owner revocation, authorization withdrawal, or 30 days after last authorized run; named secret custodian",
    "Crash cleanup": "Remove partial writes; retain only valid CurrentUser ciphertext and bounded metadata",
    "Fault owner": "SecretStore",
    "Factual or error result": "secret_root_invalid; secret_root_cleanup_failed",
    "Terminal status": "failed; acceptance blocked",
    Retryability: "false",
    "Wire version": "secret-store v1; never MCP",
  },
  {
    "Value or capability": "evidence root",
    "Persisted form": "Current-user-only directory outside the repository",
    Resolver: "F11 live evidence admission",
    "Allowed consumers": "F11 evidence store; F9 acceptance runner receives admitted references only",
    "Side-effect owner": "Named evidence custodian",
    Retention: "Through Tier 3 or Tier 4 decision, or 30 days after Tier 2",
    "Deletion trigger and owner": "Decision complete or 30-day limit; named evidence custodian",
    "Crash cleanup": "Delete every unsealed partial packet",
    "Fault owner": "F11 live evidence",
    "Factual or error result": "evidence_root_invalid; evidence_root_cleanup_failed",
    "Terminal status": "failed; acceptance blocked",
    Retryability: "false",
    "Wire version": "live-evidence v1; admitted references only",
  },
  {
    "Value or capability": "approved target identity",
    "Persisted form": "Opaque owner handle bound in outside-repository config; evidence contains only the opaque handle and mismatch dimension or reason codes, never host, tenant, posting, URL, URL hash, query, fragment, or token values",
    Resolver: "Real-run preflight and F3 persistent browser",
    "Allowed consumers": "F3 target verifier; F9 receives opaque handle and sanitized observation",
    "Side-effect owner": "F3 Browser Session Adapter",
    Retention: "Same as owner input configuration",
    "Deletion trigger and owner": "With owner input configuration; named runtime operator",
    "Crash cleanup": "Re-resolve handle and reconcile exact browser truth before reuse",
    "Fault owner": "F3 observation; F9 terminal projection",
    "Factual or error result": "target_mismatch(host, tenant, or posting); target_ambiguous; posting_unavailable(not_found, closed, removed, or unavailable)",
    "Terminal status": "blocked",
    Retryability: "none; factual terminal has no retryable flag",
    "Wire version": "live-target v1; TerminalResult v4; McpResponse v4; EventEnvelope v3",
  },
  {
    "Value or capability": "persistent browser profile",
    "Persisted form": "One isolated directory per journey and account under runtime root; no raw page capture",
    Resolver: "F3 persistent Playwright adapter",
    "Allowed consumers": "F3 only; F9 receives opaque session and page identifiers",
    "Side-effect owner": "F3 Browser Session Adapter",
    Retention: "Active journey plus 24-hour crash-recovery lease",
    "Deletion trigger and owner": "Journey terminal, stale or mismatched profile, or lease expiry; runner first, named runtime operator fallback",
    "Crash cleanup": "Delete rather than adopt stale, ambiguous, foreign, or mismatched profiles",
    "Fault owner": "F3 Browser Session Adapter",
    "Factual or error result": "existing browser errors; browser_profile_cleanup_failed",
    "Terminal status": "failed; cleanup failure blocks acceptance",
    Retryability: "browser availability only before any side effect; uncertain effects and cleanup are false",
    "Wire version": "persistent-browser v1; opaque coordinates only",
  },
  {
    "Value or capability": "account credential record",
    "Persisted form": "windows-dpapi-current-user-v1 ciphertext plus version, provider, purpose, scope, expiry, and opaque ID under secrets root; no plaintext fallback",
    Resolver: "CredentialMutationAdapter only",
    "Allowed consumers": "CredentialMutationAdapter",
    "Side-effect owner": "SecretStore for storage; F3 credential mutation for typing",
    Retention: "Authorization lifetime, capped at 30 days after last authorized run",
    "Deletion trigger and owner": "Revocation, authorization withdrawal, or retention cap; named secret custodian",
    "Crash cleanup": "Discard plaintext and partial writes; retain only valid ciphertext record",
    "Fault owner": "SecretStore or credential mutation owner",
    "Factual or error result": "secret_handle_invalid; secret_handle_expired; secret_handle_mismatched; secret_consumer_forbidden; secret_store_unavailable; account_secret_cleanup_failed",
    "Terminal status": "failed",
    Retryability: "secret_store_unavailable only; all other listed errors are false",
    "Wire version": "secret-handle v1; ErrorEnvelope v3",
  },
  {
    "Value or capability": "Gmail OAuth credential record",
    "Persisted form": "windows-dpapi-current-user-v1 ciphertext plus version, provider, purpose, scope, expiry, and opaque ID under secrets root; no OAuth bytes outside privileged memory",
    Resolver: "PrivilegedGmailAuthExecutor only",
    "Allowed consumers": "PrivilegedGmailAuthExecutor",
    "Side-effect owner": "SecretStore for storage; privileged Gmail auth executor for one authenticated call",
    Retention: "Authorization lifetime, capped at 30 days after last authorized run",
    "Deletion trigger and owner": "Revocation, authorization withdrawal, or retention cap; named secret custodian also revokes provider access",
    "Crash cleanup": "Discard OAuth plaintext and partial writes; retain only valid ciphertext record",
    "Fault owner": "SecretStore or privileged Gmail auth executor",
    "Factual or error result": "secret_handle_invalid; secret_handle_expired; secret_handle_mismatched; secret_consumer_forbidden; secret_store_unavailable; gmail_oauth_secret_cleanup_failed",
    "Terminal status": "failed",
    Retryability: "secret_store_unavailable only; all other listed errors are false",
    "Wire version": "secret-handle v1; ErrorEnvelope v3",
  },
  {
    "Value or capability": "owner input configuration",
    "Persisted form": "References and opaque handles only in s2-owner-inputs.json under runtime root; no secret values",
    Resolver: "Real-run preflight",
    "Allowed consumers": "Preflight; F9 receives validated safe references only",
    "Side-effect owner": "Named runtime operator",
    Retention: "Through Tier 3 decision or 30 days after Tier 2",
    "Deletion trigger and owner": "Decision complete, retention cap, invalid, or partial file; named runtime operator",
    "Crash cleanup": "Remove invalid or partial file and fail preflight closed",
    "Fault owner": "Real-run preflight",
    "Factual or error result": "owner_config_invalid; owner_config_cleanup_failed",
    "Terminal status": "failed; browser not started",
    Retryability: "false; renewed owner approval and valid config required",
    "Wire version": "owner-inputs v1; outside MCP request v2",
  },
  {
    "Value or capability": "typed account credential mutation",
    "Persisted form": "No plaintext, field value, receipt value, or raw page value",
    Resolver: "CredentialMutationAdapter resolves one scoped handle inside one call",
    "Allowed consumers": "Account entry handler may request mutation with opaque handle; generic drivers and F9 cannot resolve plaintext",
    "Side-effect owner": "F3 credential mutation adapter",
    Retention: "Call lifetime only",
    "Deletion trigger and owner": "Immediately after call; credential mutation adapter",
    "Crash cleanup": "Plaintext is lost; browser truth must be independently reconciled",
    "Fault owner": "F3 credential mutation adapter",
    "Factual or error result": "credential_mutation_denied; credential_effect_uncertain",
    "Terminal status": "failed",
    Retryability: "false",
    "Wire version": "credential-mutation v1; ErrorEnvelope v3",
  },
  {
    "Value or capability": "account access observation",
    "Persisted form": "Value-free structural state code only",
    Resolver: "F3 observation and Workday live classifier",
    "Allowed consumers": "F9 live coordinator; account lifecycle",
    "Side-effect owner": "F3 for browser effects; F9 for terminal projection",
    Retention: "Bounded live checkpoint and admitted event only",
    "Deletion trigger and owner": "With checkpoint or evidence retention; owning store",
    "Crash cleanup": "Re-observe browser truth before continuing",
    "Fault owner": "Classifier for observation; F9 for projection",
    "Factual or error result": "existing_account, create_account, verification_required, and application_ready are nonterminal; manual_intervention(captcha, mfa, or access_control) is factual",
    "Terminal status": "running for nonterminal states; blocked for manual_intervention",
    Retryability: "none for manual_intervention",
    "Wire version": "live-account-state v1; TerminalResult v4 when terminal",
  },
  {
    "Value or capability": "privileged Gmail query",
    "Persisted form": "No OAuth bytes, message or body bytes, subject, sender or recipient values, Gmail message or thread IDs, headers, URL, or token",
    Resolver: "gmail-api-v1 through PrivilegedGmailAuthExecutor",
    "Allowed consumers": "Gmail provider only; mailbox policy receives frozen safe result",
    "Side-effect owner": "PrivilegedGmailAuthExecutor for auth call; Gmail provider for bounded query",
    Retention: "Current journey lower bound through an exact five-minute maximum poll lifetime; the query must never widen its lower bound",
    "Deletion trigger and owner": "Immediately after each call; privileged Gmail auth executor and Gmail provider",
    "Crash cleanup": "Discard in-memory auth and message data; restart with a new journey lower bound; alternate-job recovery must use a different Workday tenant/host because verification mail does not prove posting identity",
    "Fault owner": "Privileged Gmail auth executor or Gmail provider",
    "Factual or error result": "mailbox_query_invalid; gmail_auth_denied; gmail_rate_limited; gmail_network_unavailable; mailbox_timeout",
    "Terminal status": "failed after F9 exhausts any allowed bounded retry",
    Retryability: "gmail_rate_limited, gmail_network_unavailable, and mailbox_timeout only",
    "Wire version": "gmail-api-v1; ErrorEnvelope v3",
  },
  {
    "Value or capability": "mailbox result and verification artifact handle",
    "Persisted form": "Provider enum, received-time bucket, expiry, candidate count, and opaque journey-scoped single-use handle only",
    Resolver: "MailboxProvider policy; PrivilegedVerificationNavigator alone may resolve admitted link",
    "Allowed consumers": "Account lifecycle and F9 receive safe result; PrivilegedVerificationNavigator receives admitted handle",
    "Side-effect owner": "Gmail provider for issue and consume; F9 for bounded retry and terminal projection",
    Retention: "Until consume, expiry, or journey terminal",
    "Deletion trigger and owner": "Consume, expiry, or journey terminal; Gmail provider invalidates handle state",
    "Crash cleanup": "Invalidate in-flight handle and perform bounded re-query",
    "Fault owner": "Mailbox provider for observation; F9 for projection",
    "Factual or error result": "mailbox_none; mailbox_ambiguous; mailbox_expired; mailbox_consumed; second consume or reuse is verification_artifact_replayed",
    "Terminal status": "blocked for factual outcomes after bounded policy action is exhausted",
    Retryability: "none for factual terminal; replay and second consume are false",
    "Wire version": "mailbox-result v1; TerminalResult v4; McpResponse v4; EventEnvelope v3",
  },
  {
    "Value or capability": "raw verification message, link, and token bytes",
    "Persisted form": "Never persisted; memory only inside privileged provider and navigation calls",
    Resolver: "PrivilegedGmailAuthExecutor and PrivilegedVerificationNavigator",
    "Allowed consumers": "PrivilegedGmailAuthExecutor and PrivilegedVerificationNavigator only",
    "Side-effect owner": "Gmail provider and F3 privileged verification navigator",
    Retention: "Single privileged call only",
    "Deletion trigger and owner": "Call return, cancellation, consume, or expiry; current privileged owner",
    "Crash cleanup": "Process loss discards bytes and invalidates handle",
    "Fault owner": "Current privileged owner",
    "Factual or error result": "raw_text_forbidden; token_forbidden; verification_navigation_denied",
    "Terminal status": "failed",
    Retryability: "false",
    "Wire version": "never serialized",
  },
  {
    "Value or capability": "privileged verification navigation",
    "Persisted form": "Value-free admission and structural navigation receipt only; no raw link",
    Resolver: "PrivilegedVerificationNavigator after host, tenant, recipient, time, journey, and replay admission",
    "Allowed consumers": "Account lifecycle may request admitted navigation; F9 receives sanitized result",
    "Side-effect owner": "F3 privileged verification navigator",
    Retention: "Call lifetime plus admitted value-free evidence",
    "Deletion trigger and owner": "With handle consume and evidence retention; navigator and evidence store",
    "Crash cleanup": "Treat effect as uncertain until browser truth and handle state reconcile",
    "Fault owner": "F3 privileged verification navigator",
    "Factual or error result": "verification_target_unavailable; verification_navigation_denied",
    "Terminal status": "blocked for target unavailable; failed for denied",
    Retryability: "false",
    "Wire version": "verification-navigation v1; TerminalResult v4; ErrorEnvelope v3",
  },
  {
    "Value or capability": "recovery checkpoint",
    "Persisted form": "Bounded value-free schema under runtime root; exact revision, schema, lease, opaque coordinates, and safe handle state only",
    Resolver: "Recovery classifier; F9 owns retry and resume scheduling",
    "Allowed consumers": "F9 live coordinator and recovery classifier",
    "Side-effect owner": "Checkpoint store for persistence; F9 for scheduling",
    Retention: "Active journey plus 24-hour crash-recovery lease",
    "Deletion trigger and owner": "Terminal evidence sealed, invalid checkpoint, mismatch, or lease expiry; runner first, named runtime operator fallback",
    "Crash cleanup": "Reconcile exact revision, schema, lease, target, and browser truth or delete and start fresh",
    "Fault owner": "Checkpoint store or recovery classifier; F9 only for retry exhaustion",
    "Factual or error result": "recovery_checkpoint_invalid; recovery_checkpoint_unavailable; recovery_state_ambiguous; recovery_target_mismatch; recovery_checkpoint_cleanup_failed",
    "Terminal status": "failed",
    Retryability: "recovery_checkpoint_unavailable only; all other listed errors are false",
    "Wire version": "live-checkpoint v1; DurableJourneyState remains v3; ErrorEnvelope v3",
  },
  {
    "Value or capability": "captured resume bytes",
    "Persisted form": "Never persisted; immutable memory-only capture",
    Resolver: "Verified resume artifact capture",
    "Allowed consumers": "F3 upload operation and F8 independent verifier through opaque artifact handle",
    "Side-effect owner": "F3 browser upload adapter",
    Retention: "Through independent upload verification only",
    "Deletion trigger and owner": "Verification complete, cancellation, or process exit; capture owner",
    "Crash cleanup": "Invalidate handle and require fresh source verification before another browser effect",
    "Fault owner": "Resume capture owner or F3 upload adapter",
    "Factual or error result": "existing artifact errors; resume_capture_cleanup_failed",
    "Terminal status": "failed",
    Retryability: "false until fresh source verification creates a new handle",
    "Wire version": "accepted S1 artifact contract; bytes never serialized",
  },
  {
    "Value or capability": "sanitized acceptance evidence",
    "Persisted form": "Sealed bounded acceptance.json and admitted manifest under evidence root; no personal, secret, raw page, filename, path, digest, URL, or token values",
    Resolver: "F11 live evidence admission",
    "Allowed consumers": "F9 acceptance runner, F10 factual reporting, named evidence custodian, and owner review through admitted references",
    "Side-effect owner": "F11 live evidence store",
    Retention: "Through Tier 3 or Tier 4 decision, or 30 days after Tier 2",
    "Deletion trigger and owner": "Decision complete or retention cap; named evidence custodian",
    "Crash cleanup": "Delete unsealed partials; keep only sealed same-revision packet",
    "Fault owner": "F11 live evidence store",
    "Factual or error result": "existing evidence errors; acceptance_evidence_cleanup_failed",
    "Terminal status": "failed; acceptance blocked",
    Retryability: "evidence_unavailable only inside F9 budget; admission and cleanup are false",
    "Wire version": "live-evidence v1; common admitted references retain S1 evidence version",
  },
  {
    "Value or capability": "raw DOM and screenshot capture",
    "Persisted form": "Never persisted",
    Resolver: "F3 may observe live DOM in memory; no screenshot or diagnostic capture exists in Stage 2",
    "Allowed consumers": "F3 bounded observation call only; no agent, operator, event, evidence sink, or retained artifact",
    "Side-effect owner": "F3 owns bounded observation; future diagnostic capture requires a new owner decision",
    Retention: "None",
    "Deletion trigger and owner": "Not applicable because capture is forbidden",
    "Crash cleanup": "No artifact may exist",
    "Fault owner": "F11 privacy admission",
    "Factual or error result": "raw_text_forbidden; evidence_denied",
    "Terminal status": "failed; acceptance blocked",
    Retryability: "false",
    "Wire version": "never serialized",
  },
  {
    "Value or capability": "ATS family classification",
    "Persisted form": "Reviewed ATS family ID plus sanitized structural trait IDs and counts only",
    Resolver: "F5 AtsFamilyClassifier",
    "Allowed consumers": "F9 live coordinator and Workday PageTypeClassifier",
    "Side-effect owner": "F5 classification is read-only",
    Retention: "Current observation; admitted SanitizedUnknownCandidate may follow evidence retention",
    "Deletion trigger and owner": "Observation end or evidence retention limit; F5 or F11 owning store",
    "Crash cleanup": "Discard observation and classify the fresh structural state again",
    "Fault owner": "F5 AtsFamilyClassifier",
    "Factual or error result": "ats_unsupported for every non-Workday family in S2 and S3; ats_unknown; ats_ambiguous",
    "Terminal status": "blocked",
    Retryability: "none; live classification never mutates or reloads selectors",
    "Wire version": "accepted S1 semantic contract plus live-classification v1",
  },
  {
    "Value or capability": "Workday page type classification",
    "Persisted form": "Reviewed Workday page type ID plus sanitized structural trait IDs and counts only",
    Resolver: "F5 Workday PageTypeClassifier",
    "Allowed consumers": "F9 live coordinator and UiBehaviorClassifier",
    "Side-effect owner": "F5 classification is read-only",
    Retention: "Current observation; admitted SanitizedUnknownCandidate may follow evidence retention",
    "Deletion trigger and owner": "Observation end or evidence retention limit; F5 or F11 owning store",
    "Crash cleanup": "Discard observation and classify the fresh structural state again",
    "Fault owner": "F5 Workday PageTypeClassifier",
    "Factual or error result": "workday_page_unknown; workday_page_ambiguous; ats_unsupported if ATS family is not Workday",
    "Terminal status": "blocked",
    Retryability: "none; live classification never mutates or reloads page signatures",
    "Wire version": "accepted S1 page identity plus live-classification v1",
  },
  {
    "Value or capability": "UI behavior classification",
    "Persisted form": "Canonical UI behavior ID, reviewed variant ID, and sanitized structural trait IDs and counts only",
    Resolver: "F5 UiBehaviorClassifier",
    "Allowed consumers": "F6 QuestionClassifier and F7 reviewed driver dispatch through F9",
    "Side-effect owner": "F5 classification is read-only; F7 dispatch does not change classification policy",
    Retention: "Current field observation; admitted SanitizedUnknownCandidate may follow evidence retention",
    "Deletion trigger and owner": "Observation end or evidence retention limit; F5 or F11 owning store",
    "Crash cleanup": "Discard observation and classify the fresh structural state again",
    "Fault owner": "F5 UiBehaviorClassifier",
    "Factual or error result": "ui_behavior_unknown; ui_behavior_ambiguous; ui_variant_unreviewed; driver_behavior_unsupported for a known unsupported behavior",
    "Terminal status": "blocked for factual classification; failed only for exact stable driver error",
    Retryability: "none; live classification never mutates or reloads selectors or variant registry",
    "Wire version": "accepted S1 UiBehaviorId plus live reviewed-variant v1",
  },
  {
    "Value or capability": "question classification",
    "Persisted form": "Canonical question ID plus sanitized label trait IDs, option count, and structural context IDs only",
    Resolver: "F6 QuestionClassifier",
    "Allowed consumers": "F6 canonical answer resolution through F9",
    "Side-effect owner": "F6 classification is read-only",
    Retention: "Current field resolution; admitted SanitizedUnknownCandidate may follow evidence retention",
    "Deletion trigger and owner": "Resolution end or evidence retention limit; F6 or F11 owning store",
    "Crash cleanup": "Discard candidate and classify the fresh semantic field again",
    "Fault owner": "F6 QuestionClassifier",
    "Factual or error result": "question_unknown; question_ambiguous",
    "Terminal status": "blocked",
    Retryability: "none; live classification never mutates or reloads question catalogs",
    "Wire version": "accepted S1 QuestionId plus live-classification v1",
  },
  {
    "Value or capability": "canonical answer type and provenance",
    "Persisted form": "Explicit canonical AnswerType ID, source revision, and value-free provenance ID only; applicant value remains in its accepted owner boundary",
    Resolver: "F6 AnswerResolver",
    "Allowed consumers": "F7 reviewed driver receives resolved FieldIntent through F9; no learning component receives applicant value",
    "Side-effect owner": "F6 resolution is read-only; authoritative profile, resume, job, catalog, or approved template retains value ownership",
    Retention: "Current field intent and admitted value-free provenance evidence only",
    "Deletion trigger and owner": "Intent end or evidence retention limit; F6 or F11 owning store",
    "Crash cleanup": "Discard unresolved intent and resolve again from immutable authoritative revisions",
    "Fault owner": "F6 AnswerResolver",
    "Factual or error result": "profile_answer_missing; answer_type_unknown; answer_type_ambiguous; answer_provenance_invalid",
    "Terminal status": "blocked for missing, unknown, or ambiguous; failed for invalid provenance",
    Retryability: "false; never invent, mutate, or reload applicant facts or answers",
    "Wire version": "accepted S1 FieldIntent and provenance plus canonical-answer-type v1",
  },
  {
    "Value or capability": "visible option mapping",
    "Persisted form": "Canonical option ID, visible option IDs, sanitized option count, and exact mapping outcome only; no raw option text",
    Resolver: "F6 VisibleOptionMapper",
    "Allowed consumers": "F6 AnswerResolver and F7 reviewed driver through F9",
    "Side-effect owner": "F6 mapping is read-only",
    Retention: "Current resolution; admitted SanitizedUnknownCandidate may follow evidence retention",
    "Deletion trigger and owner": "Resolution end or evidence retention limit; F6 or F11 owning store",
    "Crash cleanup": "Discard mapping and remap the fresh reviewed option set",
    "Fault owner": "F6 VisibleOptionMapper",
    "Factual or error result": "option_no_match; option_ambiguous",
    "Terminal status": "blocked",
    Retryability: "none; live mapping never mutates or reloads option aliases or catalogs",
    "Wire version": "accepted S1 option mapping plus live-classification v1",
  },
  {
    "Value or capability": "SanitizedUnknownCandidate evidence",
    "Persisted form": "Layer ID, reviewed parent IDs, sanitized structural trait IDs, counts, observed variant ID if present, source revision, and factual outcome code only",
    Resolver: "F11 live evidence admission",
    "Allowed consumers": "Named owner and between-run component reviewer; runtime classifiers receive no candidate feedback",
    "Side-effect owner": "F11 admits evidence; it cannot alter runtime policy",
    Retention: "Through Tier 3 or Tier 4 decision, or 30 days after Tier 2",
    "Deletion trigger and owner": "Decision complete or retention cap; named evidence custodian",
    "Crash cleanup": "Delete unsealed candidate evidence",
    "Fault owner": "F11 live evidence admission",
    "Factual or error result": "Original exact layer outcome remains terminal; evidence_denied if candidate is unsafe",
    "Terminal status": "Original blocked status is unchanged; evidence denial fails acceptance",
    Retryability: "false",
    "Wire version": "sanitized-unknown-candidate v1; never changes common terminal code",
  },
  {
    "Value or capability": "between-run review and promotion authority",
    "Persisted form": "Reviewed fixture, explicit source change, test evidence, reviewer decision, and new immutable revision ID only",
    Resolver: "Named human owner and named component source owner between runs",
    "Allowed consumers": "Authorized F5, F6, or F7 implementation task after owner review; no active journey",
    "Side-effect owner": "Named human owner approves; component source owner changes code or reviewed data",
    Retention: "Normal repository history and admitted review evidence after promotion",
    "Deletion trigger and owner": "Rejected candidates follow evidence retention; accepted revisions follow repository policy",
    "Crash cleanup": "Discard uncommitted promotion state; active runtime stays on its pinned revision",
    "Fault owner": "Named component source owner",
    "Factual or error result": "policy_override_forbidden for in-run mutation, selector reload, catalog reload, alias reload, applicant-fact mutation, or answer mutation",
    "Terminal status": "Active run remains blocked on its original exact outcome; forbidden promotion attempt fails",
    Retryability: "false within the run; a later separately authorized revision starts a new run",
    "Wire version": "promotion-record v1; runtime common wires unchanged",
  },
  {
    "Value or capability": "F9 live orchestration and public terminal projection",
    "Persisted form": "Value-free live checkpoint, event, terminal result, and admitted evidence references only",
    Resolver: "Single F9 live coordinator and existing MCP facade",
    "Allowed consumers": "F9 is sole loop owner; MCP facade receives common terminal protocol only",
    "Side-effect owner": "F9 for scheduling, retry, cancellation, classification, and terminal projection; providers retain their own effects",
    Retention: "Per checkpoint, event, terminal, and evidence owner policies",
    "Deletion trigger and owner": "Per owning store; F9 never deletes peer-owned resources directly",
    "Crash cleanup": "Rehydrate only admitted checkpoint state and reconcile provider truth before resume",
    "Fault owner": "Provider owner for provider fault; F9 for retry exhaustion and projection",
    "Factual or error result": "Exact live factual outcome or exact stable provider error; retry exhaustion retains last provider code and uses journey_retry_exhausted without relabeling factual results",
    "Terminal status": "blocked for factual terminal; failed for stable error; review_reached, cancelled, and running remain distinct",
    Retryability: "Only F9 spends bounded retries on errors marked true; blocked terminals have no retryable flag",
    "Wire version": "TerminalResult v4; McpResponse v4; ErrorEnvelope v3; EventEnvelope v3; McpRequest stays v2",
  },
  {
    "Value or capability": "component and review agent access",
    "Persisted form": "Sanitized synthetic fixtures and value-free review records only",
    Resolver: "No live-value resolver",
    "Allowed consumers": "Component agents and the one F0 broad reviewer at T4",
    "Side-effect owner": "None for live providers; named coordinator owns sanitized task dispatch",
    Retention: "Task and review evidence lifetime only",
    "Deletion trigger and owner": "Task close or evidence retention limit; named coordinator or evidence custodian",
    "Crash cleanup": "Discard partial agent artifacts; never recover from raw live values",
    "Fault owner": "Named coordinator for scope; F11 for admission",
    "Factual or error result": "policy_override_forbidden; evidence_denied",
    "Terminal status": "failed; acceptance blocked",
    Retryability: "false",
    "Wire version": "sanitized fixtures only; no provider wire",
  },
  {
    "Value or capability": "local custodian authority",
    "Persisted form": "Role names and value-free deletion records only",
    Resolver: "Current Windows user",
    "Allowed consumers": "Named runtime operator, named secret custodian, and named evidence custodian are one local human owner",
    "Side-effect owner": "The named custodian for each external root",
    Retention: "For the governed artifact lifetime",
    "Deletion trigger and owner": "Per resource row; no agent, service account, or second user may substitute",
    "Crash cleanup": "Named local owner performs fallback deletion when runner cleanup fails",
    "Fault owner": "The resource owner; cleanup failure remains resource-specific",
    "Factual or error result": "Resource-specific cleanup error",
    "Terminal status": "failed; acceptance blocked",
    Retryability: "false",
    "Wire version": "not serialized as authority",
  },
];

test("S2-F0-T1 freezes every live value and capability as exact rows", () => {
  const markdown = readFileSync(
    new URL("../../../docs/s2-live-boundaries.md", import.meta.url),
    "utf8",
  );
  assert.deepEqual(parseTable(markdown, "Live authority matrix"), expectedRows);
});

test("S2-F0-T1 records exact prototype dispositions", () => {
  const markdown = readFileSync(
    new URL("../../../docs/s2-live-boundaries.md", import.meta.url),
    "utf8",
  );
  assert.deepEqual(parseDispositionTable(markdown), [
    {
      artifact: "accepted-s1-tip-87c77e5",
      disposition: "REUSE",
      reason: "Only accepted Stage 1 behavior is the implementation base; S2 changes it only through the explicit F0 delta.",
    },
    {
      artifact: "v2-workday-observations",
      disposition: "SALVAGE/ADAPT",
      reason: "Use only sanitized state signatures, selector variants, repeatable controls, and no-Submit cases as new fixtures.",
    },
    {
      artifact: "v2-gmail-secret-code",
      disposition: "SCRAP/REWRITE",
      reason: "It stored or returned OAuth bytes, raw messages, identifiers, subjects, addresses, links, or tokens.",
    },
    {
      artifact: "browser-target-registry",
      disposition: "SCRAP/REWRITE",
      reason: "Raw URL, URL hash, tab ID, debug port, and arbitrary CDP ownership conflict with opaque targets and F3 ownership.",
    },
    {
      artifact: "prototype-orchestrators",
      disposition: "SCRAP/REWRITE",
      reason: "Monolithic account and mailbox loops conflict with the single F9 coordinator and bounded retry ownership.",
    },
    {
      artifact: "historical-c1-stage-2",
      disposition: "SCRAP/OUT-OF-SCOPE",
      reason: "Those files concern job discovery and LinkedIn, not C3 v3 Stage 2.",
    },
  ]);
});
