from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Any

DEFAULT_TIMEOUT_SECONDS = 120.0
MAX_CAPTURE_BYTES = 1_000_000
TERMINATION_GRACE_SECONDS = 5.0


def compile_tex(
    tex_path: str | Path,
    *,
    timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS,
) -> dict:
    tex_path = Path(tex_path)
    output_dir = tex_path.parent
    pdflatex = shutil.which("pdflatex")
    if not pdflatex:
        return {
            "compile_status": "tool_missing",
            "pdf_path": None,
            "page_count": None,
            "fits_one_page": False,
            "log_text": "pdflatex not found on PATH.",
        }

    result = _run_bounded(
        [pdflatex, "-interaction=nonstopmode", "-halt-on-error", tex_path.name],
        cwd=output_dir,
        timeout_seconds=timeout_seconds,
    )
    pdf_path = output_dir / f"{tex_path.stem}.pdf"
    successful = (
        result["status"] == "completed" and result["returncode"] == 0 and pdf_path.is_file()
    )
    page_count = None
    if successful:
        page_count = get_pdf_page_count(pdf_path)

    return {
        "compile_status": (
            "ok"
            if successful
            else result["status"]
            if result["status"] != "completed"
            else "failed"
        ),
        "pdf_path": str(pdf_path) if successful else None,
        "page_count": page_count,
        "fits_one_page": page_count == 1,
        "log_text": result["log_text"],
    }


def get_pdf_page_count(
    pdf_path: str | Path,
    *,
    timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS,
) -> int | None:
    pdfinfo = shutil.which("pdfinfo")
    if pdfinfo:
        result = _run_bounded(
            [pdfinfo, str(pdf_path)],
            cwd=Path(pdf_path).parent,
            timeout_seconds=timeout_seconds,
        )
        if result["status"] == "completed" and result["returncode"] == 0:
            for line in result["stdout"].splitlines():
                if line.startswith("Pages:"):
                    try:
                        return int(line.split(":", 1)[1].strip())
                    except ValueError:
                        return None

    # Fallback for environments without pdfinfo. The PDFs generated by our
    # LaTeX flow are simple enough that counting page objects is a useful last
    # resort when external tooling is unavailable.
    try:
        data = Path(pdf_path).read_bytes()
    except OSError:
        return None
    page_objects = len(re.findall(rb"/Type\s*/Page\b", data))
    return page_objects if page_objects > 0 else None


def _run_bounded(
    args: list[str],
    *,
    cwd: Path,
    timeout_seconds: float,
) -> dict[str, Any]:
    """Run a local compiler/tool with bounded lifetime and captured diagnostics."""
    with (
        tempfile.TemporaryFile(mode="w+b") as stdout_file,
        tempfile.TemporaryFile(mode="w+b") as stderr_file,
    ):
        try:
            process = subprocess.Popen(
                args,
                cwd=cwd,
                stdin=subprocess.DEVNULL,
                stdout=stdout_file,
                stderr=stderr_file,
                shell=False,
                creationflags=(
                    subprocess.CREATE_NO_WINDOW
                    if os.name == "nt" and hasattr(subprocess, "CREATE_NO_WINDOW")
                    else 0
                ),
            )
        except OSError as exc:
            return {
                "status": "failed",
                "returncode": None,
                "stdout": "",
                "log_text": f"Tool could not be started: {exc}",
            }

        deadline = time.monotonic() + max(0.001, timeout_seconds)
        while process.poll() is None:
            if _capture_exceeded(stdout_file) or _capture_exceeded(stderr_file):
                _terminate(process)
                return {
                    "status": "output_limit",
                    "returncode": process.returncode,
                    "stdout": "",
                    "log_text": "Compiler output exceeded the capture limit.",
                }
            if time.monotonic() >= deadline:
                _terminate(process)
                return {
                    "status": "timeout",
                    "returncode": process.returncode,
                    "stdout": "",
                    "log_text": "Compiler process exceeded its timeout.",
                }
            time.sleep(0.02)

        stdout = _read_capture(stdout_file)
        stderr = _read_capture(stderr_file)
        if stdout is None or stderr is None:
            _terminate(process)
            return {
                "status": "output_limit",
                "returncode": process.returncode,
                "stdout": "",
                "log_text": "Compiler output exceeded the capture limit.",
            }

    return {
        "status": "completed",
        "returncode": process.returncode,
        "stdout": stdout,
        "log_text": stdout + ("\n" + stderr if stderr else ""),
    }


def _terminate(process: subprocess.Popen[Any]) -> None:
    try:
        if os.name == "nt" and process.poll() is None:
            try:
                subprocess.run(
                    ["taskkill.exe", "/PID", str(process.pid), "/T", "/F"],
                    stdin=subprocess.DEVNULL,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    check=False,
                    timeout=TERMINATION_GRACE_SECONDS,
                    creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
                )
            except (OSError, subprocess.TimeoutExpired):
                pass
        if process.poll() is None:
            process.kill()
    finally:
        try:
            process.wait(timeout=TERMINATION_GRACE_SECONDS)
        except (OSError, subprocess.TimeoutExpired):
            pass


def _read_capture(stream: Any) -> str | None:
    stream.seek(0)
    value = stream.read(MAX_CAPTURE_BYTES + 1)
    if len(value) > MAX_CAPTURE_BYTES:
        return None
    return value.decode("utf-8", errors="replace")


def _capture_exceeded(stream: Any) -> bool:
    return stream.seek(0, 2) > MAX_CAPTURE_BYTES
