export const STORAGE_KEYS = {
  settings: "hunt.apply.settings",
  profile: "hunt.apply.profile",
  defaultResume: "hunt.apply.defaultResume",
  activeApplyContext: "hunt.apply.activeApplyContext",
  attempts: "hunt.apply.attempts",
  questionAnswers: "hunt.apply.questionAnswers",
  activityLog: "hunt.apply.activityLog",
};

export const DEFAULT_SETTINGS = {
  settingsVersion: 4,
  autofillOnLoad: false,
  manualFillEnabled: true,
  autoPromptEnabled: true,
  autoAccountSignupLoginEnabled: false,
  autoEmailVerificationEnabled: false,
  emailVerificationTimeoutSeconds: 90,
  autoClickNextAfterFill: false,
  fillRequiredOnly: true,
  autoExportLogs: false,
  autoExportLogPrefix: "hunt-c3-logs",
  debugLogSinkEnabled: true,
  c4PollingEnabled: false,
  backendUrl: "http://127.0.0.1:8000",
  serviceToken: "",
  pollIntervalSeconds: 60,
  heartbeatIntervalSeconds: 120,
  oneActiveRunLock: true,
  allowGeneratedAnswers: true,
  flagLowConfidenceAnswers: true,
  llmAnswerFallbackEnabled: true,
  stripLongDash: true,
};

export const DEFAULT_PROFILE = {
  fullName: "",
  email: "",
  accountEmail: "",
  accountPassword: "",
  phone: "",
  phoneDeviceType: "",
  location: "",
  linkedinUrl: "",
  githubUrl: "",
  websiteUrl: "",
  applicationSource: "",
  applicationSourceCategory: "",
  applicationSourceDetail: "",
  workAuthorized: true,
  canadianCitizenOrPermanentResident: "",
  sinStartsWithNine: "",
  sinExpiryDate: "",
  interestedTemporaryShortContract: "yes",
  disclosureGender: "",
  disclosureTransExperience: "",
  disclosureLgbqIdentity: "",
  disclosureDisability: "",
  disclosureIndigenousIdentity: "",
  disclosureVisibleMinority: "",
  disclosureVeteranStatus: "",
  sponsorshipRequired: false,
  willingToRelocate: true,
  openToAnyLocation: true,
  salaryFlexible: true,
  familyMemberAtCompany: "",
  reliabilityStatusClearance: "",
  previousDeloitteErnstYoung: "",
  languageSkillsStatement: "",
  salaryExpectationRange: "",
  coOpTermsCompleted: "",
  availableSummer2026: "",
  availableInterviewWindow: "",
  expectedGraduationYear: "",
  previousEmployers: "",
  skills: [],
  languages: [],
  workExperience: [],
  education: [],
  notes: "",
};

export const DEFAULT_RESUME = {
  label: "",
  sourceType: "manual_default",
  pdfPath: "",
  pdfFileName: "",
  pdfMimeType: "application/pdf",
  pdfDataUrl: "",
  texPath: "",
  versionId: "",
  jobId: "",
  updatedAt: null,
};

export function createEmptyApplyContext() {
  return {
    jobId: "",
    title: "",
    company: "",
    applyUrl: "",
    jobUrl: "",
    sourceMode: "manual",
    source: "",
    atsType: "",
    applyType: "",
    autoApplyEligible: false,
    description: "",
    selectedResumeVersionId: "",
    selectedResumePath: "",
    selectedResumeTexPath: "",
    selectedResumeSummary: "",
    selectedResumeName: "",
    selectedResumeMimeType: "application/pdf",
    selectedResumeDataUrl: "",
    selectedResumeReadyForC3: false,
    jdSnapshotPath: "",
    concernFlags: [],
    primedAt: null,
  };
}
