export const STORAGE_KEYS = {
  settings: "hunt.apply.settings",
  runtimeConfig: "hunt.apply.runtimeConfig",
  profile: "hunt.apply.profile",
  defaultResume: "hunt.apply.defaultResume",
  activeApplyContext: "hunt.apply.activeApplyContext",
  attempts: "hunt.apply.attempts",
  questionAnswers: "hunt.apply.questionAnswers",
  unknownQuestionDefaults: "hunt.apply.unknownQuestionDefaults",
  activityLog: "hunt.apply.activityLog",
  browserContext: "hunt.apply.browserContext",
};

export const DEFAULT_SETTINGS = {
  settingsVersion: 6,
  autofillOnLoad: false,
  manualFillEnabled: true,
  autoPromptEnabled: true,
  autoAccountSignupLoginEnabled: false,
  autoEmailVerificationEnabled: false,
  emailVerificationBridgeUrl: "http://127.0.0.1:8765/verify-email",
  emailVerificationTimeoutSeconds: 90,
  autoClickNextAfterFill: true,
  fillRequiredOnly: true,
  autoExportLogs: false,
  autoExportLogPrefix: "hunt-c3-logs",
  debugLogSinkEnabled: true,
  ledgerEnabled: false,
  ledgerBackendUrl: "",
  agentId: "",
  laneId: "",
  sessionId: "",
  leaseId: "",
  c3DeepDebugEnabled: false,
  c4PollingEnabled: false,
  backendUrl: "http://127.0.0.1:8004",
  serviceToken: "",
  pollIntervalSeconds: 60,
  heartbeatIntervalSeconds: 120,
  oneActiveRunLock: true,
  allowGeneratedAnswers: true,
  flagLowConfidenceAnswers: true,
  llmAnswerFallbackEnabled: true,
  useFieldPipelineV2: true,
  stripLongDash: true,
};

export const DEFAULT_BROWSER_CONTEXT = {
  name: "normal_chrome",
  configuredBy: "extension_default",
  configuredAt: "",
};

export const DEFAULT_RUNTIME_CONFIG = {
  backendUrl: "",
  serviceToken: "",
  debugLogSinkEnabled: null,
  ledgerEnabled: null,
  ledgerBackendUrl: "",
  agentId: "",
  laneId: "",
  sessionId: "",
  leaseId: "",
  c3DeepDebugEnabled: null,
  autoClickNextAfterFill: null,
  autoAccountSignupLoginEnabled: null,
  autoEmailVerificationEnabled: null,
  emailVerificationTimeoutSeconds: null,
  configuredBy: "",
  configuredAt: "",
};

export const DEFAULT_PROFILE = {
  fullName: "",
  email: "",
  accountEmail: "",
  accountPassword: "",
  phone: "",
  phoneDeviceType: "",
  phoneCountryCode: "",
  location: "",
  city: "",
  province: "",
  country: "",
  middleName: "",
  namePrefix: "",
  nameSuffix: "",
  addressLine1: "",
  addressLine2: "",
  postalCode: "",
  linkedinUrl: "",
  githubUrl: "",
  websiteUrl: "",
  applicationSource: "",
  applicationSourceCategory: "",
  applicationSourceDetail: "",
  workAuthorized: true,
  canadianCitizenOrPermanentResident: "",
  sinStartsWithNine: "",
  sinExpiryDate: "",
  interestedTemporaryShortContract: "yes",
  disclosureGender: "",
  disclosureTransExperience: "",
  disclosureLgbqIdentity: "",
  disclosureDisability: "",
  disclosureIndigenousIdentity: "",
  disclosureVisibleMinority: "",
  disclosureVeteranStatus: "",
  accommodationRequest: "",
  sponsorshipRequired: false,
  willingToRelocate: true,
  openToAnyLocation: true,
  salaryFlexible: true,
  compensationOfferFactors: false,
  conflictOfInterestRelationship: false,
  hhsOigExcluded: false,
  gsaFederalProgramExcluded: false,
  genericDrugDebarred: false,
  debarmentProceedingsPending: false,
  usLicensedPhysician: false,
  fdaHhsInvestigationalDrugRestricted: false,
  governmentalLicensingInquiry: false,
  familyMemberAtCompany: "",
  reliabilityStatusClearance: "",
  previousDeloitteErnstYoung: "",
  languageSkillsStatement: "",
  salaryExpectation: "",
  salaryExpectationRange: "",
  hourlyPayExpectation: "",
  coOpTermsCompleted: "",
  availableSummer2026: "",
  availableInterviewWindow: "",
  expectedGraduationYear: "",
  degreeLevel: "",
  highestEducation: "",
  preferredEducationIndex: "",
  previousEmployers: "",
  skills: [],
  languages: [],
  workExperience: [],
  education: [],
  notes: "",
};

export const DEFAULT_RESUME = {
  label: "",
  sourceType: "manual_default",
  pdfPath: "",
  pdfFileName: "",
  pdfMimeType: "application/pdf",
  pdfDataUrl: "",
  texPath: "",
  versionId: "",
  jobId: "",
  updatedAt: null,
};

export function createEmptyApplyContext() {
  return {
    jobId: "",
    title: "",
    company: "",
    applyUrl: "",
    jobUrl: "",
    sourceMode: "manual",
    source: "",
    atsType: "",
    applyType: "",
    autoApplyEligible: false,
    description: "",
    selectedResumeVersionId: "",
    selectedResumePath: "",
    selectedResumeTexPath: "",
    selectedResumeSummary: "",
    selectedResumeName: "",
    selectedResumeMimeType: "application/pdf",
    selectedResumeDataUrl: "",
    selectedResumeReadyForC3: false,
    jdSnapshotPath: "",
    concernFlags: [],
    primedAt: null,
  };
}
